//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEBookConsoleLoad
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public string LoadMasterLoader { get; set; }
        public string LoadMAWBNo { get; set; }
        public string MAWBNoExtra { get; set; }
        public string LoadCarrier { get; set; }
        public Nullable<int> LoadDSTN { get; set; }
        public string LoadArea { get; set; }
        public Nullable<System.DateTime> LoadDate { get; set; }
        public string LoadFLTNo { get; set; }
        public Nullable<System.DateTime> LoadETD { get; set; }
        public Nullable<System.DateTime> LoadETA { get; set; }
        public Nullable<System.DateTime> LoadATD { get; set; }
        public Nullable<System.DateTime> LoadATA { get; set; }
        public Nullable<int> LoadPCS { get; set; }
        public string LoadPCSType { get; set; }
        public Nullable<decimal> LoadWeight { get; set; }
        public string LoadWeightType { get; set; }
        public Nullable<decimal> LoadVolume { get; set; }
        public string LoadVolumeType { get; set; }
        public Nullable<decimal> LoadVWT { get; set; }
        public string LoadTerminal { get; set; }
        public string LoadPallet { get; set; }
        public string LoadStatus { get; set; }
        public string LoadEstCost { get; set; }
        public string LoadRemark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remark { get; set; }
        public string LoadMasterLoadName { get; set; }
        public Nullable<int> DEPT1 { get; set; }
        public Nullable<int> DSTN1 { get; set; }
        public string FLTNo1 { get; set; }
        public Nullable<System.DateTime> ETD1 { get; set; }
        public Nullable<System.DateTime> ETA1 { get; set; }
        public Nullable<System.DateTime> ATD1 { get; set; }
        public Nullable<System.DateTime> ATA1 { get; set; }
        public Nullable<int> DEPT2 { get; set; }
        public Nullable<int> DSTN2 { get; set; }
        public string FLTNo2 { get; set; }
        public Nullable<System.DateTime> ETD2 { get; set; }
        public Nullable<System.DateTime> ETA2 { get; set; }
        public Nullable<System.DateTime> ATD2 { get; set; }
        public Nullable<System.DateTime> ATA2 { get; set; }
        public string Status { get; set; }
    }
}
