//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEColoadBooking
    {
        public int ID { get; set; }
        public int BookingID { get; set; }
        public Nullable<int> ColoadID { get; set; }
        public string LinkStation { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<int> DSTN { get; set; }
        public Nullable<int> Shipper { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAddress { get; set; }
        public Nullable<int> ShipperMap { get; set; }
        public Nullable<int> CNEE { get; set; }
        public string CNEEName { get; set; }
        public string CNEEAddress { get; set; }
        public Nullable<int> CNEEMap { get; set; }
        public Nullable<int> Notify { get; set; }
        public string NotifyName { get; set; }
        public string NotifyAddress { get; set; }
        public Nullable<int> NotifyMap { get; set; }
        public Nullable<System.DateTime> AvailDate { get; set; }
        public Nullable<System.DateTime> DeptDate { get; set; }
        public Nullable<System.DateTime> ArriDate { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public string GWTUOM { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string VolumeUOM { get; set; }
        public string Descript { get; set; }
        public string ExportLIC { get; set; }
        public string CommINV { get; set; }
        public string Quantity { get; set; }
        public string Remarks { get; set; }
        public string Marks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string Status { get; set; }
        public string AWBType { get; set; }
        public Nullable<int> HAWBID { get; set; }
        public string ServiceLevel { get; set; }
        public string DocType { get; set; }
        public string Rate { get; set; }
        public string Carrier { get; set; }
    }
}
