//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEHAWBPO
    {
        public int ID { get; set; }
        public int HAWBID { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PlaceOfDELV { get; set; }
        public string Item { get; set; }
        public string InvoiceNo { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string POExtra1 { get; set; }
        public string POExtra2 { get; set; }
        public string POExtra3 { get; set; }
        public string POExtra4 { get; set; }
        public string POExtra5 { get; set; }
        public string POExtra6 { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string SONO { get; set; }
        public Nullable<int> SCTNS { get; set; }
        public string Curr { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> POMSID { get; set; }
        public string UOM { get; set; }
    }
}
