//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEMAWB
    {
        public int ID { get; set; }
        public string MAWBNo { get; set; }
        public string Other { get; set; }
        public string FRT { get; set; }
        public Nullable<int> MAWBType { get; set; }
        public Nullable<int> IssueCity { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string LotNo { get; set; }
        public Nullable<double> GWT { get; set; }
        public Nullable<double> CWT { get; set; }
        public string Currency { get; set; }
        public Nullable<double> Show { get; set; }
        public Nullable<double> CTCT { get; set; }
        public Nullable<double> Comm { get; set; }
        public Nullable<double> ExComm { get; set; }
        public Nullable<int> Issuer { get; set; }
        public Nullable<int> Shipper { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> Notify { get; set; }
        public string WTUOM { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<int> PCS { get; set; }
        public string ClassRate { get; set; }
        public string SPINST { get; set; }
        public string Status { get; set; }
        public string PackagingDescription { get; set; }
        public Nullable<int> PortOfDEPT { get; set; }
        public Nullable<int> PortOfDSTN { get; set; }
        public Nullable<int> PrintPerson { get; set; }
        public Nullable<double> DueToAgent { get; set; }
        public Nullable<double> DueToCarrier { get; set; }
        public string PreAlertBy { get; set; }
        public Nullable<System.DateTime> LastPreAlertTime { get; set; }
        public Nullable<System.DateTime> LasteManifestTime { get; set; }
        public string eManifestBy { get; set; }
        public string IssuerType { get; set; }
        public string isAMS { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string CYMNo { get; set; }
        public Nullable<double> VWT { get; set; }
        public Nullable<int> SPL { get; set; }
        public string DBID { get; set; }
        public string AMSBy { get; set; }
        public Nullable<System.DateTime> AMSDate { get; set; }
        public string ReWeight { get; set; }
        public string WeightBy { get; set; }
        public Nullable<System.DateTime> WeightDate { get; set; }
        public Nullable<double> DIM { get; set; }
        public string DIMUOM { get; set; }
        public string AWBStatus { get; set; }
        public Nullable<int> AirportOfDEPT { get; set; }
        public Nullable<int> AirportOfDSTN { get; set; }
    }
}
