//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEPOD
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public int HAWBID { get; set; }
        public string FLTNo { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string SCHReleaseNo { get; set; }
        public Nullable<System.DateTime> SCHReleaseDate { get; set; }
        public Nullable<int> SCHNotifyParty { get; set; }
        public Nullable<System.DateTime> SCHNotifyDate { get; set; }
        public Nullable<int> SCHDocReleaseParty { get; set; }
        public Nullable<System.DateTime> SCHDocReleaseDate { get; set; }
        public string SCHDocReleaseType { get; set; }
        public string SCHNotifyType { get; set; }
        public string SCHCargoSignBy { get; set; }
        public Nullable<System.DateTime> SCHLicenseDate { get; set; }
        public Nullable<System.DateTime> SCHCustomDate { get; set; }
        public string SCHDocSignBy { get; set; }
        public Nullable<int> SCHCargoReleaseParty { get; set; }
        public Nullable<System.DateTime> SCHCargoReleaseDate { get; set; }
        public string SCHCargoReleaseType { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string PODTemplate { get; set; }
        public Nullable<System.DateTime> SCHCargoTerminalDate { get; set; }
    }
}
