//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIAuthToMakeEntry
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public int HAWBID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string ImportOn { get; set; }
        public string VIA { get; set; }
        public string From { get; set; }
        public string FlightNO { get; set; }
        public string MAWBNO { get; set; }
        public string ITNo { get; set; }
        public string EntryPort { get; set; }
        public string LotNo { get; set; }
        public string HAWBNo { get; set; }
        public string FreightLoc { get; set; }
        public string HAWB { get; set; }
        public string SubHAWB { get; set; }
        public string DESC { get; set; }
        public string PCS { get; set; }
        public string Weight { get; set; }
        public string DueTo { get; set; }
        public string Storage { get; set; }
        public string Consignee { get; set; }
        public string AuthoriseTo { get; set; }
        public string AttorneyInFact { get; set; }
        public string Broker { get; set; }
        public string MCHEDImport { get; set; }
        public string ITDate { get; set; }
        public Nullable<int> FormTitle { get; set; }
        public Nullable<int> AuthorizeCondition { get; set; }
        public string ChargeList { get; set; }
        public Nullable<int> IsShowChrg { get; set; }
    }
}
