//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AICarrierBooking
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public int MAWBID { get; set; }
        public int DEPT { get; set; }
        public int DSTN { get; set; }
        public string BookedFLT { get; set; }
        public string OnboardFLT { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<double> GWT { get; set; }
        public Nullable<double> CWT { get; set; }
        public Nullable<double> VWT { get; set; }
        public Nullable<int> SourceID { get; set; }
    }
}
