//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIEntry
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public int MAWBID { get; set; }
        public string Damage { get; set; }
        public string Shortage { get; set; }
        public string Offload { get; set; }
        public Nullable<System.DateTime> CustomsDate { get; set; }
        public string CustomsEntry { get; set; }
        public Nullable<int> EntryPort { get; set; }
        public string FLTNo { get; set; }
        public Nullable<int> CargoAt { get; set; }
        public Nullable<int> TotalPCS { get; set; }
        public Nullable<double> GWT { get; set; }
        public string EntryType { get; set; }
        public string Storage { get; set; }
        public Nullable<System.DateTime> LandingDate { get; set; }
        public Nullable<int> Carrier { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> Carriers { get; set; }
        public Nullable<int> Avail { get; set; }
        public string AvailAddr { get; set; }
        public Nullable<System.DateTime> AvailDate { get; set; }
    }
}
