//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIHAWBPickup
    {
        public MongoDB.Bson.ObjectId _id { get; set; }
        public int ID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Truck { get; set; }
        public Nullable<System.DateTime> ActualPickup { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsPickup { get; set; }
        public int PickupFrom { get; set; }
        public Nullable<System.DateTime> AvailPickup { get; set; }
        public int HAWBID { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string VehicleNo { get; set; }
        public string Driver { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> DELVTo { get; set; }
        public string DELVAddr { get; set; }
        public Nullable<double> Weight { get; set; }
        public string WeightUOM { get; set; }
        public Nullable<System.DateTime> ActualPickupTo { get; set; }
        public Nullable<System.DateTime> AvailPickupTo { get; set; }
        public Nullable<double> CWT { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public string SendBy { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> ConsolePickupID { get; set; }
        public Nullable<int> ConsoleCount { get; set; }
        public string InvolvedBy { get; set; }
    }
}
