//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATARLegalCaseLog
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string LegalNo { get; set; }
        public string PL { get; set; }
        public Nullable<int> CustomerHQID { get; set; }
        public string CreditApproval { get; set; }
        public string Master { get; set; }
        public string House { get; set; }
        public string InvoiceNo { get; set; }
        public string OrgCurr { get; set; }
        public Nullable<decimal> OrgAmt { get; set; }
        public Nullable<decimal> AROutstandAmt { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<decimal> AROutstandAmt_Home { get; set; }
    }
}
