//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATMonthlyAROutstandingHistory_DelDup_170602
    {
        public int ID { get; set; }
        public string Period { get; set; }
        public string PL { get; set; }
        public Nullable<int> CustomerHQID { get; set; }
        public string CreditApproval { get; set; }
        public string CreditLimitCurr { get; set; }
        public string CreditLimit { get; set; }
        public string HouseNo { get; set; }
        public string OrgCurr { get; set; }
        public Nullable<decimal> OrgAmount { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> AROutstandingAmt { get; set; }
        public string OwnerStation { get; set; }
        public string LeadOwner { get; set; }
        public string Issuer { get; set; }
        public string SalesPerson { get; set; }
        public Nullable<decimal> NotOverDue { get; set; }
        public Nullable<decimal> Range1 { get; set; }
        public Nullable<decimal> Range2 { get; set; }
        public Nullable<decimal> Range3 { get; set; }
        public Nullable<decimal> Range4 { get; set; }
        public Nullable<decimal> Range5 { get; set; }
        public Nullable<decimal> Range6 { get; set; }
        public Nullable<decimal> Range7 { get; set; }
        public Nullable<decimal> Range8 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
