//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATMonthlyKPI
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string EvaPeriod { get; set; }
        public Nullable<decimal> K1Result { get; set; }
        public Nullable<decimal> K1V1 { get; set; }
        public Nullable<decimal> K1V2 { get; set; }
        public string K1Rank { get; set; }
        public Nullable<decimal> K2Result { get; set; }
        public Nullable<decimal> K2V1 { get; set; }
        public Nullable<decimal> K2V2 { get; set; }
        public string K2Rank { get; set; }
        public Nullable<decimal> K3Result { get; set; }
        public Nullable<decimal> K3V1 { get; set; }
        public Nullable<decimal> K3V2 { get; set; }
        public string K3Rank { get; set; }
        public Nullable<decimal> K4Result { get; set; }
        public Nullable<decimal> K4V1 { get; set; }
        public Nullable<decimal> K4V2 { get; set; }
        public string K4Rank { get; set; }
        public Nullable<decimal> K5Result1 { get; set; }
        public Nullable<decimal> K5Result2 { get; set; }
        public Nullable<decimal> K5V1 { get; set; }
        public Nullable<decimal> K5V2 { get; set; }
        public string K5Rank1 { get; set; }
        public Nullable<decimal> K5V3 { get; set; }
        public Nullable<decimal> K5V4 { get; set; }
        public string K5Rank2 { get; set; }
        public Nullable<decimal> K6Result { get; set; }
        public Nullable<decimal> K6V1 { get; set; }
        public Nullable<decimal> K6V2 { get; set; }
        public Nullable<decimal> K6V3 { get; set; }
        public Nullable<decimal> K6V4 { get; set; }
        public Nullable<decimal> K6V5 { get; set; }
        public Nullable<decimal> K6V6 { get; set; }
        public Nullable<decimal> K7Result { get; set; }
        public Nullable<decimal> K7V1 { get; set; }
        public Nullable<decimal> K7V2 { get; set; }
        public Nullable<decimal> K7V3 { get; set; }
        public Nullable<decimal> K7V4 { get; set; }
        public Nullable<decimal> K7V5 { get; set; }
        public Nullable<decimal> K7V6 { get; set; }
        public Nullable<decimal> K8Result { get; set; }
        public Nullable<decimal> K8V1 { get; set; }
        public Nullable<decimal> K8V2 { get; set; }
        public Nullable<decimal> K8V3 { get; set; }
        public Nullable<decimal> K8V4 { get; set; }
        public Nullable<decimal> K8V5 { get; set; }
        public Nullable<decimal> K8V6 { get; set; }
        public Nullable<decimal> K9Result { get; set; }
        public Nullable<decimal> K9V1 { get; set; }
        public Nullable<decimal> K9V2 { get; set; }
        public Nullable<decimal> K9V3 { get; set; }
        public Nullable<decimal> K9V4 { get; set; }
        public Nullable<decimal> K9V5 { get; set; }
        public Nullable<decimal> K9V6 { get; set; }
        public Nullable<decimal> K10Result { get; set; }
        public Nullable<decimal> K10V1 { get; set; }
        public Nullable<decimal> K10V2 { get; set; }
        public Nullable<decimal> K10V3 { get; set; }
        public Nullable<decimal> K10V4 { get; set; }
        public Nullable<decimal> K10V5 { get; set; }
        public Nullable<decimal> K10V6 { get; set; }
        public Nullable<decimal> K6ExLegal { get; set; }
        public Nullable<decimal> K7ExLegal { get; set; }
        public Nullable<decimal> K9ExLegal { get; set; }
        public Nullable<decimal> K10ExLegal { get; set; }
    }
}
