//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBak
    {
        public int ReportID { get; set; }
        public string UserID { get; set; }
        public System.DateTime BuildTime { get; set; }
        public string RepName { get; set; }
        public string RepCategory { get; set; }
        public string XMLData { get; set; }
        public string CSXMLData { get; set; }
        public string CSType { get; set; }
    }
}
