//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOAWBSUM
    {
        public string STATIONID { get; set; }
        public int SourceID { get; set; }
        public string IDType { get; set; }
        public Nullable<double> FRT_ECOST { get; set; }
        public Nullable<double> Other_ECOST { get; set; }
        public Nullable<double> Extra_ECOST { get; set; }
        public Nullable<double> Extra_FRT_ECost { get; set; }
        public Nullable<double> Extra_Other_ECost { get; set; }
        public Nullable<double> FVAT_ECOST { get; set; }
        public Nullable<double> OVAT_ECOST { get; set; }
        public Nullable<double> EVAT_ECOST { get; set; }
        public Nullable<double> EFVAT_ECOST { get; set; }
        public Nullable<double> EOVAT_ECOST { get; set; }
        public Nullable<double> FRT_Sales_PP { get; set; }
        public Nullable<double> Other_Sales_PP { get; set; }
        public Nullable<double> Extra_Sales_PP { get; set; }
        public Nullable<double> Extra_FRT_Sales_PP { get; set; }
        public Nullable<double> Extra_Other_Sales_PP { get; set; }
        public Nullable<double> FVAT_Sales_PP { get; set; }
        public Nullable<double> OVAT_Sales_PP { get; set; }
        public Nullable<double> EVAT_Sales_PP { get; set; }
        public Nullable<double> EFVAT_Sales_PP { get; set; }
        public Nullable<double> EOVAT_Sales_PP { get; set; }
        public Nullable<double> FRT_Sales_CC { get; set; }
        public Nullable<double> Other_Sales_CC { get; set; }
        public Nullable<double> Extra_Sales_CC { get; set; }
        public Nullable<double> Extra_FRT_Sales_CC { get; set; }
        public Nullable<double> Extra_Other_Sales_CC { get; set; }
        public Nullable<double> FVAT_Sales_CC { get; set; }
        public Nullable<double> OVAT_Sales_CC { get; set; }
        public Nullable<double> EVAT_Sales_CC { get; set; }
        public Nullable<double> EFVAT_Sales_CC { get; set; }
        public Nullable<double> EOVAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_FRT_ECOST { get; set; }
        public Nullable<double> Rpt_Other_ECOST { get; set; }
        public Nullable<double> Rpt_Extra_ECOST { get; set; }
        public Nullable<double> Rpt_Extra_FRT_ECost { get; set; }
        public Nullable<double> Rpt_Extra_Other_ECost { get; set; }
        public Nullable<double> Rpt_FVAT_ECOST { get; set; }
        public Nullable<double> Rpt_OVAT_ECOST { get; set; }
        public Nullable<double> Rpt_EVAT_ECOST { get; set; }
        public Nullable<double> Rpt_EFVAT_ECOST { get; set; }
        public Nullable<double> Rpt_EOVAT_ECOST { get; set; }
        public Nullable<double> Rpt_FRT_Sales_PP { get; set; }
        public Nullable<double> Rpt_Other_Sales_PP { get; set; }
        public Nullable<double> Rpt_Extra_Sales_PP { get; set; }
        public Nullable<double> Rpt_Extra_FRT_Sales_PP { get; set; }
        public Nullable<double> Rpt_Extra_Other_Sales_PP { get; set; }
        public Nullable<double> Rpt_FVAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_OVAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_EVAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_EFVAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_EOVAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_FRT_Sales_CC { get; set; }
        public Nullable<double> Rpt_Other_Sales_CC { get; set; }
        public Nullable<double> Rpt_Extra_Sales_CC { get; set; }
        public Nullable<double> Rpt_Extra_FRT_Sales_CC { get; set; }
        public Nullable<double> Rpt_Extra_Other_Sales_CC { get; set; }
        public Nullable<double> Rpt_FVAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_OVAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_EVAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_EFVAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_EOVAT_Sales_CC { get; set; }
        public string ReportCurrency { get; set; }
        public string LocalCurrency { get; set; }
        public int ID { get; set; }
        public byte[] Version { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<double> CUS_Sales_PP { get; set; }
        public Nullable<double> CUS_VAT_Sales_PP { get; set; }
        public Nullable<double> Extra_CUS_Sales_PP { get; set; }
        public Nullable<double> Extra_CUS_VAT_Sales_PP { get; set; }
        public Nullable<double> CUS_Sales_CC { get; set; }
        public Nullable<double> CUS_VAT_Sales_CC { get; set; }
        public Nullable<double> Extra_CUS_Sales_CC { get; set; }
        public Nullable<double> Extra_CUS_VAT_Sales_CC { get; set; }
        public Nullable<double> CUS_ECOST { get; set; }
        public Nullable<double> CUS_VAT_ECOST { get; set; }
        public Nullable<double> Extra_CUS_ECOST { get; set; }
        public Nullable<double> Extra_CUS_VAT_ECOST { get; set; }
        public Nullable<double> DNDim_Ecost { get; set; }
        public Nullable<double> DNDIm_Cus_Ecost { get; set; }
        public Nullable<double> Extra_DNDim_Ecost { get; set; }
        public Nullable<double> Extra_DNDIm_Cus_Ecost { get; set; }
        public Nullable<double> Rpt_CUS_Sales_PP { get; set; }
        public Nullable<double> Rpt_CUS_VAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_Extra_CUS_Sales_PP { get; set; }
        public Nullable<double> Rpt_Extra_CUS_VAT_Sales_PP { get; set; }
        public Nullable<double> Rpt_CUS_Sales_CC { get; set; }
        public Nullable<double> Rpt_CUS_VAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_Extra_CUS_Sales_CC { get; set; }
        public Nullable<double> Rpt_Extra_CUS_VAT_Sales_CC { get; set; }
        public Nullable<double> Rpt_CUS_ECOST { get; set; }
        public Nullable<double> Rpt_CUS_VAT_ECOST { get; set; }
        public Nullable<double> Rpt_Extra_CUS_ECOST { get; set; }
        public Nullable<double> Rpt_Extra_CUS_VAT_ECOST { get; set; }
        public Nullable<double> Rpt_DNDim_Ecost { get; set; }
        public Nullable<double> Rpt_DNDIm_Cus_Ecost { get; set; }
        public Nullable<double> Rpt_Extra_DNDim_Ecost { get; set; }
        public Nullable<double> Rpt_Extra_DNDIm_Cus_Ecost { get; set; }
    }
}
