//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOBookingReturn
    {
        public int ID { get; set; }
        public int MBLID { get; set; }
        public string StationID { get; set; }
        public string Party { get; set; }
        public string PLoading { get; set; }
        public string PDischarge { get; set; }
        public string MBLNo { get; set; }
        public string Vessel { get; set; }
        public string ETD { get; set; }
        public string CBM { get; set; }
        public string PDischargeDateFrom { get; set; }
        public string PDischargeDateTo { get; set; }
        public string CustomsETD { get; set; }
        public string GoodsInDate { get; set; }
        public string PlaceOfPacking { get; set; }
        public string Tel { get; set; }
        public string ContactPerson { get; set; }
        public string Remark { get; set; }
        public string CTN20 { get; set; }
        public string CTN40 { get; set; }
        public string CTNHC { get; set; }
        public string CTNOthers { get; set; }
        public string Mode { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
    }
}
