//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLogDetails
    {
        public int Id { get; set; }
        public string EntryClass { get; set; }
        public string FunctionName { get; set; }
        public string FunctionParameters { get; set; }
        public string ClientIP { get; set; }
        public string ExceptionMessage { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<decimal> ExecutionSeconds { get; set; }
    }
}
