//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMBL
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string MBLNo { get; set; }
        public string LotNo { get; set; }
        public string PONo { get; set; }
        public Nullable<int> SrcMBLID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string CarrierName { get; set; }
        public string CarrierInfo { get; set; }
        public string MoveType { get; set; }
        public string HBLType { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string ReqDate { get; set; }
        public Nullable<int> PReceipt { get; set; }
        public string PReceipe_Name { get; set; }
        public Nullable<int> PLoading { get; set; }
        public string PLoading_Name { get; set; }
        public Nullable<int> PDischarge { get; set; }
        public string PDischarge_Name { get; set; }
        public Nullable<int> PDelivery { get; set; }
        public string PDelivery_Name { get; set; }
        public Nullable<int> SHPR { get; set; }
        public string SHPRName { get; set; }
        public string SHAddress1 { get; set; }
        public string SHAddress2 { get; set; }
        public string SHAddress3 { get; set; }
        public string SHAddress4 { get; set; }
        public string SHAddress5 { get; set; }
        public string SHAddress6 { get; set; }
        public Nullable<int> CNEE { get; set; }
        public string CNEEName { get; set; }
        public string CNAddress1 { get; set; }
        public string CNAddress2 { get; set; }
        public string CNAddress3 { get; set; }
        public string CNAddress4 { get; set; }
        public string CNAddress5 { get; set; }
        public string CNAddress6 { get; set; }
        public Nullable<int> NTFY { get; set; }
        public string NTFYName { get; set; }
        public string NPAddress1 { get; set; }
        public string NPAddress2 { get; set; }
        public string NPAddress3 { get; set; }
        public string NPAddress4 { get; set; }
        public string NPAddress5 { get; set; }
        public string NPAddress6 { get; set; }
        public string HSCode { get; set; }
        public string CargoID { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public string PCSType { get; set; }
        public Nullable<double> TareWT { get; set; }
        public Nullable<double> VOL { get; set; }
        public Nullable<double> GrossWT { get; set; }
        public string FreightClause { get; set; }
        public string NoOBL { get; set; }
        public string IssueCode { get; set; }
        public string SODescription { get; set; }
        public string Instruction { get; set; }
        public string DG_Class { get; set; }
        public string DG_Page { get; set; }
        public string DG_UNNO { get; set; }
        public string DG_Lable { get; set; }
        public string DG_FlashP { get; set; }
        public string DG_Group { get; set; }
        public string DG_EMS { get; set; }
        public string DG_MFAG { get; set; }
        public string DG_MPT { get; set; }
        public string DG_EmergencyContract { get; set; }
        public string DG_EmergencyPerson { get; set; }
        public string DG_EmergencyTel { get; set; }
        public string TemperatureSet { get; set; }
        public string TempUnit { get; set; }
        public string SendUserName { get; set; }
        public string SendTel { get; set; }
        public string SendFax { get; set; }
        public string Sendmail { get; set; }
        public string ETD { get; set; }
        public string Salesname { get; set; }
        public string ShipToDoor { get; set; }
        public string ShipToDoorAddress1 { get; set; }
        public string ShipToDoorAddress2 { get; set; }
        public string ShipToDoorAddress3 { get; set; }
        public string ShipToDoorAddress4 { get; set; }
        public string ShipToDoorName { get; set; }
        public string ShipToDoorTel { get; set; }
        public string ShipDoorTo { get; set; }
        public string ShipDoorToAddress1 { get; set; }
        public string ShipDoorToAddress2 { get; set; }
        public string ShipDoorToAddress3 { get; set; }
        public string ShipDoorToAddress4 { get; set; }
        public string ShipDoorToName { get; set; }
        public string ShipDoorTel { get; set; }
        public string GoodsDesc1 { get; set; }
        public string GoodsDesc2 { get; set; }
        public string GoodsDesc3 { get; set; }
        public string GoodsDesc4 { get; set; }
        public string GoodsDesc5 { get; set; }
        public string GoodsDesc6 { get; set; }
        public string Marks1 { get; set; }
        public string Marks2 { get; set; }
        public string Marks3 { get; set; }
        public string Marks4 { get; set; }
        public string Marks5 { get; set; }
        public string Marks6 { get; set; }
        public string NatureOfGoods { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string Status { get; set; }
        public string SOSeaWay { get; set; }
        public string SOTelex { get; set; }
        public string SOPayType { get; set; }
        public string SOPayFor { get; set; }
        public string ModeType { get; set; }
        public string SOContractNo { get; set; }
    }
}
