//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPInputCapital
    {
        public string StationID { get; set; }
        public int Year { get; set; }
        public int Seq { get; set; }
        public Nullable<int> ProductLine { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<byte> InputVersion { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Actu_Estm { get; set; }
        public Nullable<decimal> Budget_pre { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int ID { get; set; }
    }
}
