//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPInputOPInfo
    {
        public string StationID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string Budget { get; set; }
        public Nullable<byte> InputVersion { get; set; }
        public Nullable<decimal> Headcount { get; set; }
        public Nullable<decimal> Headcount_Avg { get; set; }
        public Nullable<decimal> KGS_AE { get; set; }
        public Nullable<decimal> KGS_AI { get; set; }
        public Nullable<decimal> KGS_TMS { get; set; }
        public Nullable<decimal> KGS_DE { get; set; }
        public Nullable<decimal> KGS_DI { get; set; }
        public Nullable<decimal> TEU_OE { get; set; }
        public Nullable<decimal> CBM_OE { get; set; }
        public Nullable<decimal> TEU_OI { get; set; }
        public Nullable<decimal> CBM_OI { get; set; }
        public Nullable<decimal> No_AE { get; set; }
        public Nullable<decimal> No_AI { get; set; }
        public Nullable<decimal> No_CCA { get; set; }
        public Nullable<decimal> No_OE_TEU { get; set; }
        public Nullable<decimal> No_OE_CBM { get; set; }
        public Nullable<decimal> No_OI_TEU { get; set; }
        public Nullable<decimal> No_OI_CBM { get; set; }
        public Nullable<decimal> No_CCO { get; set; }
        public Nullable<decimal> No_Warehousing { get; set; }
        public Nullable<decimal> No_TMS { get; set; }
        public Nullable<decimal> No_3PS { get; set; }
        public Nullable<decimal> No_Transshipment { get; set; }
        public Nullable<decimal> No_DE { get; set; }
        public Nullable<decimal> No_DI { get; set; }
        public Nullable<decimal> Revenue_AE { get; set; }
        public Nullable<decimal> Revenue_AI { get; set; }
        public Nullable<decimal> Revenue_CCA { get; set; }
        public Nullable<decimal> Revenue_OE { get; set; }
        public Nullable<decimal> Revenue_OI { get; set; }
        public Nullable<decimal> Revenue_CCO { get; set; }
        public Nullable<decimal> Revenue_Warehousing { get; set; }
        public Nullable<decimal> Revenue_TMS { get; set; }
        public Nullable<decimal> Revenue_3PS { get; set; }
        public Nullable<decimal> Revenue_Transshipment { get; set; }
        public Nullable<decimal> Revenue_DE { get; set; }
        public Nullable<decimal> Revenue_DI { get; set; }
        public Nullable<decimal> Revenue_Others { get; set; }
        public Nullable<decimal> Cost_AE { get; set; }
        public Nullable<decimal> Cost_AI { get; set; }
        public Nullable<decimal> Cost_CCA { get; set; }
        public Nullable<decimal> Cost_OE { get; set; }
        public Nullable<decimal> Cost_OI { get; set; }
        public Nullable<decimal> Cost_CCO { get; set; }
        public Nullable<decimal> Cost_Warehousing { get; set; }
        public Nullable<decimal> Cost_TMS { get; set; }
        public Nullable<decimal> Cost_3PS { get; set; }
        public Nullable<decimal> Cost_Transshipment { get; set; }
        public Nullable<decimal> Cost_DE { get; set; }
        public Nullable<decimal> Cost_DI { get; set; }
        public Nullable<decimal> Cost_Others { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> ExRateActual { get; set; }
        public Nullable<decimal> ExRateBudget_pre { get; set; }
        public Nullable<decimal> ExRateBudget { get; set; }
        public Nullable<decimal> NonOperating { get; set; }
        public Nullable<decimal> Revenue_OE_LCL { get; set; }
        public Nullable<decimal> Revenue_OI_LCL { get; set; }
        public Nullable<decimal> Cost_OE_LCL { get; set; }
        public Nullable<decimal> Cost_OI_LCL { get; set; }
    }
}
