//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPTonnageDaily
    {
        public int ID { get; set; }
        public System.DateTime CalcDate { get; set; }
        public Nullable<short> EndofMonth { get; set; }
        public string StationID { get; set; }
        public Nullable<int> AEHAWBNO { get; set; }
        public Nullable<decimal> AEHAWBWT { get; set; }
        public Nullable<int> AEDAWBNO { get; set; }
        public Nullable<decimal> AEDAWBWT { get; set; }
        public Nullable<int> AECoLoadHAWBNO { get; set; }
        public Nullable<decimal> AECoLoadHAWBWT { get; set; }
        public Nullable<decimal> AESalesHome { get; set; }
        public Nullable<decimal> AESalesUSD { get; set; }
        public Nullable<decimal> AECostHome { get; set; }
        public Nullable<decimal> AECostUSD { get; set; }
        public Nullable<int> AIHAWBNO { get; set; }
        public Nullable<decimal> AIHAWBWT { get; set; }
        public Nullable<decimal> AISalesHome { get; set; }
        public Nullable<decimal> AISalesUSD { get; set; }
        public Nullable<decimal> AICostHome { get; set; }
        public Nullable<decimal> AICostUSD { get; set; }
        public Nullable<int> CCANO { get; set; }
        public Nullable<decimal> CCASalesHome { get; set; }
        public Nullable<decimal> CCASalesUSD { get; set; }
        public Nullable<decimal> CCACostHome { get; set; }
        public Nullable<decimal> CCACostUSD { get; set; }
        public Nullable<int> OEFCLHBLNO { get; set; }
        public Nullable<decimal> OEFCLTEU { get; set; }
        public Nullable<decimal> OEFCLSalesHome { get; set; }
        public Nullable<decimal> OEFCLSalesUSD { get; set; }
        public Nullable<decimal> OEFCLCostHome { get; set; }
        public Nullable<decimal> OEFCLCostUSD { get; set; }
        public Nullable<int> OELCLHBLNO { get; set; }
        public Nullable<decimal> OELCLCBM { get; set; }
        public Nullable<decimal> OELCLSalesHome { get; set; }
        public Nullable<decimal> OELCLSalesUSD { get; set; }
        public Nullable<decimal> OELCLCostHome { get; set; }
        public Nullable<decimal> OELCLCostUSD { get; set; }
        public Nullable<int> OIFCLHBLNO { get; set; }
        public Nullable<decimal> OIFCLTEU { get; set; }
        public Nullable<decimal> OIFCLSalesHome { get; set; }
        public Nullable<decimal> OIFCLSalesUSD { get; set; }
        public Nullable<decimal> OIFCLCostHome { get; set; }
        public Nullable<decimal> OIFCLCostUSD { get; set; }
        public Nullable<int> OILCLHBLNO { get; set; }
        public Nullable<decimal> OILCLCBM { get; set; }
        public Nullable<decimal> OILCLSalesHome { get; set; }
        public Nullable<decimal> OILCLSalesUSD { get; set; }
        public Nullable<decimal> OILCLCostHome { get; set; }
        public Nullable<decimal> OILCLCostUSD { get; set; }
        public Nullable<int> CCONO { get; set; }
        public Nullable<decimal> CCOSalesHome { get; set; }
        public Nullable<decimal> CCOSalesUSD { get; set; }
        public Nullable<decimal> CCOCostHome { get; set; }
        public Nullable<decimal> CCOCostUSD { get; set; }
        public Nullable<int> WMNO { get; set; }
        public Nullable<decimal> WMSalesHome { get; set; }
        public Nullable<decimal> WMSalesUSD { get; set; }
        public Nullable<decimal> WMCostHome { get; set; }
        public Nullable<decimal> WMCostUSD { get; set; }
        public Nullable<int> TruckNo { get; set; }
        public Nullable<decimal> TruckWT { get; set; }
        public Nullable<decimal> TruckSalesHome { get; set; }
        public Nullable<decimal> TruckSalesUSD { get; set; }
        public Nullable<decimal> TruckCostHome { get; set; }
        public Nullable<decimal> TruckCostUSD { get; set; }
        public Nullable<int> CBSTruckNo { get; set; }
        public Nullable<decimal> CBSTruckWT { get; set; }
        public Nullable<int> CBSDistributionNo { get; set; }
        public Nullable<decimal> CBSDistributionWT { get; set; }
        public Nullable<int> TPAirNo { get; set; }
        public Nullable<decimal> TPASalesHome { get; set; }
        public Nullable<decimal> TPASalesUSD { get; set; }
        public Nullable<decimal> TPACostHome { get; set; }
        public Nullable<decimal> TPACostUSD { get; set; }
        public Nullable<int> TPONo { get; set; }
        public Nullable<decimal> TPOSalesHome { get; set; }
        public Nullable<decimal> TPOSalesUSD { get; set; }
        public Nullable<decimal> TPOCostHome { get; set; }
        public Nullable<decimal> TPOCostUSD { get; set; }
        public Nullable<int> TranShipNo { get; set; }
        public Nullable<decimal> TranShipSalesHome { get; set; }
        public Nullable<decimal> TranShipSalesUSD { get; set; }
        public Nullable<decimal> TranShipCostHome { get; set; }
        public Nullable<decimal> TranShipCostUSD { get; set; }
        public Nullable<int> DEHAWBNO { get; set; }
        public Nullable<decimal> DEHAWBWT { get; set; }
        public Nullable<decimal> DESalesHome { get; set; }
        public Nullable<decimal> DESalesUSD { get; set; }
        public Nullable<decimal> DECostHome { get; set; }
        public Nullable<decimal> DECostUSD { get; set; }
        public Nullable<int> DEDAWBNO { get; set; }
        public Nullable<decimal> DEDAWBWT { get; set; }
        public Nullable<int> DETRUCKNO { get; set; }
        public Nullable<decimal> DETRUCKWT { get; set; }
        public Nullable<int> DIHAWBNo { get; set; }
        public Nullable<decimal> DIHAWBWT { get; set; }
        public Nullable<decimal> DISalesHome { get; set; }
        public Nullable<decimal> DISalesUSD { get; set; }
        public Nullable<decimal> DICostHome { get; set; }
        public Nullable<decimal> DICostUSD { get; set; }
        public Nullable<decimal> OtherSalesHome { get; set; }
        public Nullable<decimal> OtherSalesUSD { get; set; }
        public Nullable<decimal> OtherCostHome { get; set; }
        public Nullable<decimal> OtherCostUSD { get; set; }
        public Nullable<int> CBSTRSNO { get; set; }
        public Nullable<int> CBSWMSNO { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string StatusReason { get; set; }
        public Nullable<decimal> AEMAWBWT { get; set; }
        public Nullable<decimal> AIMAWBWT { get; set; }
        public Nullable<int> AEMAWBCount { get; set; }
        public Nullable<int> AEClosedMAWBCount { get; set; }
        public Nullable<int> AIMAWBCount { get; set; }
        public Nullable<int> AIClosedMAWBCount { get; set; }
        public Nullable<int> OEMLCount { get; set; }
        public Nullable<int> OEMLClosedCount { get; set; }
        public Nullable<int> OIMLCount { get; set; }
        public Nullable<int> OIMLClosedCount { get; set; }
        public Nullable<int> DECount { get; set; }
        public Nullable<int> DEClosedCount { get; set; }
        public Nullable<int> DICount { get; set; }
        public Nullable<int> DIClosedCount { get; set; }
        public Nullable<int> TPACount { get; set; }
        public Nullable<int> TPAClosedCount { get; set; }
        public Nullable<int> TPOCount { get; set; }
        public Nullable<int> TPOClosedCount { get; set; }
        public Nullable<int> CCCount { get; set; }
        public Nullable<int> CCClosedCount { get; set; }
    }
}
