//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAApply_WorkFlow
    {
        public int ID { get; set; }
        public Nullable<int> ApplyID { get; set; }
        public string YYMonth { get; set; }
        public string StationID { get; set; }
        public Nullable<int> PNo { get; set; }
        public Nullable<short> Step { get; set; }
        public string ApproveBy { get; set; }
        public string EventCode { get; set; }
        public string EventDesc { get; set; }
        public string StepStatus { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string SendBy { get; set; }
        public string ReceiveID { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ApplyMemo { get; set; }
        public string ReplyMemo { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string GroupLevel { get; set; }
        public string SearchShow { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> SendMailDate { get; set; }
        public string SendMailMsg { get; set; }
    }
}
