//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBBrokerageDeliveryCommodity
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<double> Packages { get; set; }
        public string PackagesUOM { get; set; }
        public Nullable<double> Weight { get; set; }
        public string WeightUOM { get; set; }
        public Nullable<double> Volume { get; set; }
        public string VolumeUOM { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string UNDG { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
