//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBDCEntryInvoiceItem
    {
        public int ID { get; set; }
        public int InvoiceID { get; set; }
        public string ItemNo { get; set; }
        public string ExportCountry { get; set; }
        public string OriginCountry { get; set; }
        public string HTS { get; set; }
        public Nullable<decimal> HTSValue { get; set; }
        public Nullable<decimal> HMF { get; set; }
        public Nullable<decimal> MPF { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public Nullable<decimal> ADDDuty { get; set; }
        public Nullable<decimal> CVDDuty { get; set; }
        public Nullable<decimal> Duty { get; set; }
        public string ProductName { get; set; }
        public string AdditionalHTS1 { get; set; }
        public string AdditionalHTS2 { get; set; }
        public string AdditionalHTS3 { get; set; }
        public string AdditionalHTS4 { get; set; }
        public string AdditionalHTS5 { get; set; }
        public string ManufacturerID { get; set; }
        public Nullable<decimal> DutyRate { get; set; }
        public string DutyRateUOM { get; set; }
        public Nullable<decimal> CMBDutyRate { get; set; }
    }
}
