//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMArticle
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> ContentTypeID { get; set; }
        public string Content { get; set; }
        public string Publisher { get; set; }
        public string Source { get; set; }
        public string Attachments { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
