//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPLog
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string LogType { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> EventDT { get; set; }
        public string EventCode { get; set; }
        public string URL { get; set; }
        public string EventParameter { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
    }
}
