//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRptChart
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public string ChartTitle { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string IsInternal { get; set; }
        public string IsDisplayInHome { get; set; }
        public string ChartType { get; set; }
        public string HorizontalTitle { get; set; }
        public string HorizontalType { get; set; }
        public string TimeItem { get; set; }
        public string LaneItem { get; set; }
        public string DayType { get; set; }
        public string LaneType { get; set; }
        public string SpecColumn { get; set; }
        public string VerticalTitle { get; set; }
        public string IsShowValue { get; set; }
        public string MilestoneID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Status { get; set; }
    }
}
