//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEHAWBPreview
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStaionID { get; set; }
        public Nullable<int> HAWBID { get; set; }
        public string HAWBNO { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string MAWBNO { get; set; }
        public Nullable<int> SHPR { get; set; }
        public string SHPRCompanyName { get; set; }
        public string SHPRAddress1 { get; set; }
        public string SHPRAddress2 { get; set; }
        public string SHPRAddress3 { get; set; }
        public string SHPRAddress4 { get; set; }
        public string SHPRAddress5 { get; set; }
        public string SHPRName { get; set; }
        public string SHPRTel { get; set; }
        public Nullable<int> CNEE { get; set; }
        public string CNEECompanyName { get; set; }
        public string CNEEAddress1 { get; set; }
        public string CNEEAddress2 { get; set; }
        public string CNEEAddress3 { get; set; }
        public string CNEEAddress4 { get; set; }
        public string CNEEAddress5 { get; set; }
        public string CNEEName { get; set; }
        public string CNEETel { get; set; }
        public string ModeAir { get; set; }
        public string ModeRoad { get; set; }
        public string ModeRailWay { get; set; }
        public string ModeOther { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<int> DSTN { get; set; }
        public string Description { get; set; }
        public string PCS { get; set; }
        public string Weight { get; set; }
        public string Dimension { get; set; }
        public string Package { get; set; }
        public string Value { get; set; }
        public string UrgentDispatch { get; set; }
        public string Insurance { get; set; }
        public string Total { get; set; }
        public string IsDangerous { get; set; }
        public string Move { get; set; }
        public string PayType { get; set; }
        public string IsInsurance { get; set; }
        public string UseCNEEReceipt { get; set; }
        public string SHPRTimeRequest { get; set; }
        public string Delivery { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
    }
}
