//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMAWBPreview
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string DEPT { get; set; }
        public string DEST { get; set; }
        public string SHPR { get; set; }
        public string CNEE { get; set; }
        public string AccountingInfo { get; set; }
        public string AgentName { get; set; }
        public string To1 { get; set; }
        public string Carrier1 { get; set; }
        public string To2 { get; set; }
        public string Carrier2 { get; set; }
        public string To3 { get; set; }
        public string Carrier3 { get; set; }
        public Nullable<System.DateTime> FlightAndDate1 { get; set; }
        public Nullable<System.DateTime> FlightAndDate2 { get; set; }
        public string DeclareValue { get; set; }
        public string InsuranceAmount { get; set; }
        public string HandlingInfo { get; set; }
        public string OtherCharges { get; set; }
        public string GoodsDesc { get; set; }
        public string WeightChargePP { get; set; }
        public string ValuationChargePP { get; set; }
        public string SurfaceChargePP { get; set; }
        public string WeightChargeCC { get; set; }
        public string ValuationChargeCC { get; set; }
        public string SurfaceChargeCC { get; set; }
        public string OtherChargePP { get; set; }
        public string OtherChargeCC { get; set; }
        public string Payment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public string PCS { get; set; }
        public string GWT { get; set; }
        public string RateClass { get; set; }
        public string CommItemNo { get; set; }
        public string CWT { get; set; }
        public string Rate { get; set; }
        public string WeightCharge { get; set; }
        public string PrepaidTotal { get; set; }
        public string CollectTotal { get; set; }
        public string ExecutedDate { get; set; }
        public string ExecutedPlace { get; set; }
        public string ExecutedBy { get; set; }
        public string Flight1 { get; set; }
        public string Flight2 { get; set; }
    }
}
