//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMAWB
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> Issuer { get; set; }
        public string MAWBNo { get; set; }
        public string LotNo { get; set; }
        public string MAWBType { get; set; }
        public Nullable<int> IssueCity { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<int> DSTN { get; set; }
        public string FRT { get; set; }
        public string Other { get; set; }
        public Nullable<int> ColoadIn { get; set; }
        public Nullable<int> SHPR { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> NTFY { get; set; }
        public Nullable<int> BillTo { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<int> CSPerson { get; set; }
        public string SHPTType { get; set; }
        public Nullable<int> Terminal { get; set; }
        public string Move { get; set; }
        public string Mode { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<double> SPUnit { get; set; }
        public string SPUnitUOM { get; set; }
        public Nullable<double> NWT { get; set; }
        public string NWTUOM { get; set; }
        public Nullable<double> GWT { get; set; }
        public string GWTUOM { get; set; }
        public Nullable<double> CWT { get; set; }
        public string CWTUOM { get; set; }
        public string RateClass { get; set; }
        public string CUR { get; set; }
        public Nullable<double> SHOW { get; set; }
        public Nullable<double> CTCT { get; set; }
        public Nullable<double> COMM { get; set; }
        public Nullable<double> ExCOMM { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Net { get; set; }
        public string Marks { get; set; }
        public string NatureOfGoods { get; set; }
        public string Status { get; set; }
        public string eManifest { get; set; }
        public string IsBookmark { get; set; }
        public string IsColoadIn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> BookingPCS { get; set; }
        public string BookingPCSUOM { get; set; }
        public Nullable<int> BookingSPUnit { get; set; }
        public string BookingSPUnitUOM { get; set; }
        public Nullable<double> BookingNWT { get; set; }
        public Nullable<double> BookingGWT { get; set; }
        public Nullable<double> BookingCWT { get; set; }
        public string eMainfestBy { get; set; }
        public Nullable<System.DateTime> eMainfestDT { get; set; }
        public string IssuerType { get; set; }
        public Nullable<int> Customer { get; set; }
        public string TransferStatus { get; set; }
        public Nullable<double> Rate { get; set; }
        public string ShowRate { get; set; }
        public string QuoteType { get; set; }
        public Nullable<int> ThirdParty { get; set; }
        public string DE3PManifestSendBy { get; set; }
        public Nullable<System.DateTime> DE3PManifestSendDT { get; set; }
    }
}
