//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEOrderPO
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> HAWBID { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string PONo { get; set; }
        public string ItemNo { get; set; }
        public Nullable<int> ShipQTY { get; set; }
        public Nullable<System.DateTime> InvDate { get; set; }
        public string InvNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public string IsDAWB { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string SONO { get; set; }
        public Nullable<int> ShipCTNS { get; set; }
        public string UOM { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
    }
}
