//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIControlBank
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string BorrowIn { get; set; }
        public Nullable<System.DateTime> BorrowOutDate { get; set; }
        public string BorrowOutBy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public string UsedBy { get; set; }
        public string LotNo { get; set; }
        public string Status { get; set; }
        public string BorrowOutAgent { get; set; }
        public Nullable<int> Issuer { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
    }
}
