//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIDimension
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> HAWBID { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public string DIMUOM { get; set; }
        public Nullable<int> PCS { get; set; }
        public string Factor { get; set; }
        public Nullable<double> VolWT { get; set; }
        public string WTUOM { get; set; }
        public Nullable<double> CUFT { get; set; }
        public Nullable<double> CBM { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string IsDAWB { get; set; }
    }
}
