//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimCustomer
    {
        public int CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string GlobalCode { get; set; }
        public string CustType { get; set; }
        public int IndustryGroupID { get; set; }
        public string IndustryGroupName { get; set; }
        public int IndustryID { get; set; }
        public string IndustryCode { get; set; }
        public string IndustryName { get; set; }
    }
}
