//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimFromDIMParty
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string DimDistrictCode { get; set; }
        public string DimDistrictName { get; set; }
        public string DimCountryCode { get; set; }
        public string DimCountryName { get; set; }
        public string DimRegionCode { get; set; }
        public string DimRegionName { get; set; }
    }
}
