//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimParty
    {
        public string CustomerCode { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> isStation { get; set; }
        public Nullable<int> isForeignAgent { get; set; }
        public int isJV { get; set; }
        public string PartyType { get; set; }
    }
}
