//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIPOD
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> HAWBID { get; set; }
        public string ReleaseNO { get; set; }
        public Nullable<System.DateTime> ReleaseDT { get; set; }
        public string NotifyPartyBorker { get; set; }
        public Nullable<System.DateTime> NotifyPartyCNEEDT { get; set; }
        public Nullable<System.DateTime> LicenseDT { get; set; }
        public Nullable<System.DateTime> CustomsDT { get; set; }
        public string DocBorker { get; set; }
        public Nullable<System.DateTime> DocCNEEDT { get; set; }
        public string DocSignBy { get; set; }
        public string FRTReleaseBorker { get; set; }
        public Nullable<System.DateTime> FRTReleaseCNEEDT { get; set; }
        public string FRTReleaseSignBy { get; set; }
        public string PayType { get; set; }
        public string ChequeNO { get; set; }
        public Nullable<System.DateTime> ChequeDT { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public string PaymentSignedBy { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string NotifyPartyCheck { get; set; }
        public string DocReleaseCheck { get; set; }
        public string FRTReleaseCheck { get; set; }
        public string IsDAWB { get; set; }
    }
}
