//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI214NORTEL
    {
        public int DB_ID { get; set; }
        public string STATION { get; set; }
        public int JOBNUM { get; set; }
        public string SOURCE { get; set; }
        public Nullable<int> SRC_JOBNUM { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string SENT_BY { get; set; }
        public Nullable<System.DateTime> SENT_DATE { get; set; }
        public string B1001 { get; set; }
        public string B1002 { get; set; }
        public string B1003 { get; set; }
        public string REQ_SEND { get; set; }
        public Nullable<bool> AF { get; set; }
        public Nullable<bool> P1 { get; set; }
        public Nullable<bool> AG { get; set; }
        public Nullable<bool> K1 { get; set; }
        public Nullable<bool> OA { get; set; }
        public Nullable<bool> D1 { get; set; }
        public Nullable<int> VERSION { get; set; }
    }
}
