//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI214NORTEL4
    {
        public int DB_ID { get; set; }
        public string STATION { get; set; }
        public int JOBNUM { get; set; }
        public int ASSIGNED_LINE { get; set; }
        public int LINE { get; set; }
        public string CD304 { get; set; }
        public string CD305 { get; set; }
        public string CD307 { get; set; }
        public string CD308 { get; set; }
        public string CD311 { get; set; }
        public string CD312 { get; set; }
        public string CD313 { get; set; }
        public string N102 { get; set; }
    }
}
