//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_AMSAWB
    {
        public int ID { get; set; }
        public string ShipperInfo { get; set; }
        public Nullable<int> MAWBID { get; set; }
        public string CNEEInfo { get; set; }
        public string IssuingAgentInfo { get; set; }
        public string AgentCode { get; set; }
        public string PortOfDEPT { get; set; }
        public string ArriveOne { get; set; }
        public string ArriveTwo { get; set; }
        public string ArriveThree { get; set; }
        public string FLTOne { get; set; }
        public string FLTTwo { get; set; }
        public string FLTThree { get; set; }
        public string PortOfDSTN { get; set; }
        public string HandlingInfo { get; set; }
        public string IssuerInfo { get; set; }
        public string NotifyInfo { get; set; }
        public string Currency { get; set; }
        public string FrtPayType { get; set; }
        public string OtherPayType { get; set; }
        public string DecForCarriage { get; set; }
        public string DecForCustoms { get; set; }
        public string AmountOfIns { get; set; }
        public string WeightCharge { get; set; }
        public string TotalAmount { get; set; }
        public string OtherCharges { get; set; }
        public string SHPRCertify { get; set; }
        public string CarrierCertify { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<double> GWT { get; set; }
        public string WTUOM { get; set; }
        public string RateClass { get; set; }
        public Nullable<double> CWT { get; set; }
        public Nullable<double> Rate { get; set; }
        public string MAWBNo { get; set; }
        public string NatureOfGoods { get; set; }
        public string NatureOfGoods1 { get; set; }
        public string NatureOfGoods2 { get; set; }
        public string NatureOfGoods3 { get; set; }
        public string NatureOfGoods4 { get; set; }
        public string ShipperName { get; set; }
        public string CNEEName { get; set; }
        public string IssuingAgentName { get; set; }
        public string NotifyName { get; set; }
        public string PayTypeInfo { get; set; }
        public string PrepaidDueAgent { get; set; }
        public string CollectDueAgent { get; set; }
        public string PrepaidDueCarrier { get; set; }
        public string CollectDueCarrier { get; set; }
        public string TotalPrepaid { get; set; }
        public string TotalCollect { get; set; }
        public string PrepaidValuation { get; set; }
        public string CollectValuation { get; set; }
        public string CollectTax { get; set; }
        public string PrepaidTax { get; set; }
        public Nullable<int> TotalPCS { get; set; }
        public Nullable<double> TotalGWT { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Marks { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string StationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> CNEE_AltAddID { get; set; }
        public Nullable<int> Shipper_AltAddID { get; set; }
        public string PrintBy { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string CANNo { get; set; }
        public string FootShow { get; set; }
        public string LotNo { get; set; }
        public string TradeTerm { get; set; }
        public string SHPRCustomerName { get; set; }
        public string SHPRAddress { get; set; }
        public string SHPRCityFullName { get; set; }
        public string SHPRZipCode { get; set; }
        public string CNEECustomerName { get; set; }
        public string CNEEAddress { get; set; }
        public string CNEECityFullName { get; set; }
        public string CNEEZipCode { get; set; }
        public string CarrierBookings { get; set; }
        public string AMSType { get; set; }
    }
}
