//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVAlertLog
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int AlertID { get; set; }
        public string KeyValue { get; set; }
        public string OrderNo { get; set; }
        public short AlertType { get; set; }
        public short Via { get; set; }
        public string SendTo { get; set; }
        public Nullable<int> ORG { get; set; }
        public Nullable<int> DSTN { get; set; }
        public string ServiceLevel { get; set; }
        public short SendStatus { get; set; }
        public short SendTimes { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string MailSubject { get; set; }
        public string MailContent { get; set; }
        public string FailReason { get; set; }
        public Nullable<System.DateTime> M1Value { get; set; }
        public Nullable<System.DateTime> M2Value { get; set; }
        public Nullable<short> M1UTCOffset { get; set; }
        public Nullable<short> M2UTCOffset { get; set; }
        public Nullable<int> SendToHQID { get; set; }
        public Nullable<int> DocRefID { get; set; }
        public Nullable<short> ShipmentType { get; set; }
        public Nullable<short> UserType { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
