//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTOMS
    {
        public int SID { get; set; }
        public string StationID { get; set; }
        public string Mode { get; set; }
        public string LotType { get; set; }
        public string LotNo { get; set; }
        public string MBLNo { get; set; }
        public string HBLNo { get; set; }
        public string AWBType { get; set; }
        public Nullable<int> MBLNum { get; set; }
        public Nullable<int> HBLNum { get; set; }
        public Nullable<int> DBLNum { get; set; }
        public string CargoType { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> SHPR { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> PReceipt { get; set; }
        public Nullable<int> PortOfDEPT { get; set; }
        public Nullable<int> PortOfDSTN { get; set; }
        public Nullable<int> PDelivery { get; set; }
        public Nullable<int> Carrier { get; set; }
        public Nullable<System.DateTime> PReceiptETD { get; set; }
        public Nullable<System.DateTime> POLETD { get; set; }
        public Nullable<System.DateTime> PODETD { get; set; }
        public Nullable<System.DateTime> PDeliveryETD { get; set; }
        public Nullable<decimal> CTN20 { get; set; }
        public Nullable<decimal> CTN40 { get; set; }
        public Nullable<decimal> CTN40H { get; set; }
        public Nullable<decimal> CTN45 { get; set; }
        public Nullable<decimal> TEU { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public string SCurrency { get; set; }
        public string HomeCurrency { get; set; }
        public Nullable<decimal> PPSAMT { get; set; }
        public Nullable<decimal> PPSVAMT { get; set; }
        public Nullable<decimal> PPSTAMT { get; set; }
        public Nullable<decimal> PPSHAMT { get; set; }
        public Nullable<decimal> PPSVHAMT { get; set; }
        public Nullable<decimal> PPSHTAMT { get; set; }
        public Nullable<decimal> CCSAMT { get; set; }
        public Nullable<decimal> CCSVAMT { get; set; }
        public Nullable<decimal> CCSTAMT { get; set; }
        public Nullable<decimal> CCSHAMT { get; set; }
        public Nullable<decimal> CCSVHAMT { get; set; }
        public Nullable<decimal> CCSHTAMT { get; set; }
        public string ECurrency { get; set; }
        public Nullable<decimal> EAMT { get; set; }
        public Nullable<decimal> EVAMT { get; set; }
        public Nullable<decimal> ETAMT { get; set; }
        public Nullable<decimal> EHAMT { get; set; }
        public Nullable<decimal> EVHAMT { get; set; }
        public Nullable<decimal> EHTAMT { get; set; }
        public string ACurrency { get; set; }
        public Nullable<decimal> AAMT { get; set; }
        public Nullable<decimal> AVAMT { get; set; }
        public Nullable<decimal> ATAMT { get; set; }
        public Nullable<decimal> AHAMT { get; set; }
        public Nullable<decimal> AVHAMT { get; set; }
        public Nullable<decimal> AHTAMT { get; set; }
        public Nullable<System.DateTime> LotCreatedDate { get; set; }
        public Nullable<int> HSHPR { get; set; }
        public Nullable<int> HCNEE { get; set; }
        public string ShptType { get; set; }
    }
}
