//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMAPDetailData
    {
        public int ID { get; set; }
        public string Period { get; set; }
        public string StationID { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> VenderID { get; set; }
        public string APType { get; set; }
        public Nullable<decimal> OpenAmount { get; set; }
        public Nullable<decimal> HOpenAmount { get; set; }
        public Nullable<decimal> DocAmount { get; set; }
        public Nullable<decimal> HDocAmount { get; set; }
        public Nullable<System.DateTime> PostGLDate { get; set; }
        public string JournalNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> RopenAmount { get; set; }
        public Nullable<System.DateTime> DocCreatedDt { get; set; }
    }
}
