//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMARAgingByPeriod
    {
        public int ID { get; set; }
        public string HCurr { get; set; }
        public string StationID { get; set; }
        public string Period { get; set; }
        public string CustomerName { get; set; }
        public int BillTo { get; set; }
        public Nullable<decimal> HGroup1 { get; set; }
        public Nullable<decimal> HGroup2 { get; set; }
        public Nullable<decimal> HGroup3 { get; set; }
        public Nullable<decimal> HGroup4 { get; set; }
        public Nullable<decimal> HGroup5 { get; set; }
        public Nullable<decimal> HGroup6 { get; set; }
        public Nullable<decimal> HGroup7 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> AROverdueHGroup1 { get; set; }
        public Nullable<decimal> AROverdueHGroup2 { get; set; }
        public Nullable<decimal> AROverdueHGroup3 { get; set; }
        public Nullable<decimal> AROverdueHGroup4 { get; set; }
        public Nullable<decimal> AROverdueHGroup5 { get; set; }
        public Nullable<decimal> AROverdueHGroup6 { get; set; }
        public Nullable<decimal> AROverdueHGroup7 { get; set; }
        public Nullable<decimal> AROverdueTotal { get; set; }
    }
}
