//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMARDetailData__
    {
        public int ID { get; set; }
        public string Period { get; set; }
        public string StationID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> BillTo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string HouseNo { get; set; }
        public string MasterNo { get; set; }
        public string LotNo { get; set; }
        public string Description { get; set; }
        public string BillAddress { get; set; }
        public string ProductLine { get; set; }
        public string ModeCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<double> BookRate { get; set; }
        public string PayTerms { get; set; }
        public string CreditTermCode { get; set; }
        public string IDType { get; set; }
        public Nullable<System.DateTime> PostGLDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> BaseDate { get; set; }
        public string ConfirmBy { get; set; }
        public string SalesPerson { get; set; }
        public Nullable<int> GLARDays { get; set; }
        public Nullable<int> INVARDays { get; set; }
        public string TaxInvoice { get; set; }
        public Nullable<decimal> DutyAmount { get; set; }
        public Nullable<bool> isPS { get; set; }
        public Nullable<bool> isAutoPS { get; set; }
        public Nullable<decimal> ROpenAmount { get; set; }
        public Nullable<decimal> RHOpenAmount { get; set; }
        public Nullable<decimal> RHInvoiceAmount { get; set; }
        public Nullable<decimal> RInvoiceAmount { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
