//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMARRevHistory
    {
        public string StationID { get; set; }
        public string MonthEndPeriod { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string InvoiceCurrency { get; set; }
        public Nullable<decimal> OpenAmount { get; set; }
        public Nullable<decimal> BookRate { get; set; }
        public Nullable<decimal> HOpenAmount { get; set; }
        public Nullable<decimal> MonthEndBookRate { get; set; }
        public Nullable<System.DateTime> MonthEndDate { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> UnrealizedExchange { get; set; }
        public string JournalNo { get; set; }
        public string RJournalNo { get; set; }
        public string ChartofAccount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
    }
}
