//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMDailyARbyCustomer
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> AppCredit { get; set; }
        public string CreditCurr { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CreditApplyBy { get; set; }
        public decimal ARRange1 { get; set; }
        public decimal ARRange2 { get; set; }
        public decimal ARRange3 { get; set; }
        public decimal ARRange4 { get; set; }
        public decimal ARRange5 { get; set; }
        public decimal ARRange6 { get; set; }
        public decimal ARRange7 { get; set; }
        public decimal ARRange8 { get; set; }
        public decimal TotalAR { get; set; }
        public Nullable<decimal> CreditLimitHome { get; set; }
        public Nullable<decimal> OverDueAR { get; set; }
        public Nullable<decimal> RateToUSD { get; set; }
        public string StationID { get; set; }
        public Nullable<System.DateTime> RecentlyInvoiceDate { get; set; }
        public string RecentlyInvoiceNo { get; set; }
        public Nullable<decimal> OverDueRange1 { get; set; }
        public Nullable<decimal> OverDueRange2 { get; set; }
        public Nullable<decimal> OverDueRange3 { get; set; }
        public Nullable<decimal> OverDueRange4 { get; set; }
        public Nullable<decimal> OverDueRange5 { get; set; }
        public Nullable<decimal> OverDueRange6 { get; set; }
        public Nullable<decimal> OverDueRange7 { get; set; }
        public Nullable<decimal> OverDueRange8 { get; set; }
        public Nullable<decimal> TotalAR_3PS { get; set; }
        public Nullable<decimal> TotalAR_AMS { get; set; }
        public Nullable<decimal> TotalAR_CBS { get; set; }
        public Nullable<decimal> TotalAR_DAS { get; set; }
        public Nullable<decimal> TotalAR_OMS { get; set; }
        public Nullable<decimal> TotalAR_TMS { get; set; }
        public Nullable<decimal> TotalAR_WMS { get; set; }
        public Nullable<decimal> TotalAR_TRS { get; set; }
        public Nullable<decimal> TotalAR_IMS { get; set; }
        public Nullable<decimal> TotalAR_CBA { get; set; }
        public Nullable<decimal> TotalAR_FMS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreditRef { get; set; }
    }
}
