//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMGLBudgetEntryTemp
    {
        public string StationID { get; set; }
        public string Year { get; set; }
        public string VersionEntry { get; set; }
        public string CurrencyCode { get; set; }
        public string Unit { get; set; }
        public string Department { get; set; }
        public string ChartOfAccount { get; set; }
        public Nullable<decimal> M1 { get; set; }
        public Nullable<decimal> M2 { get; set; }
        public Nullable<decimal> M3 { get; set; }
        public Nullable<decimal> M4 { get; set; }
        public Nullable<decimal> M5 { get; set; }
        public Nullable<decimal> M6 { get; set; }
        public Nullable<decimal> M7 { get; set; }
        public Nullable<decimal> M8 { get; set; }
        public Nullable<decimal> M9 { get; set; }
        public Nullable<decimal> M10 { get; set; }
        public Nullable<decimal> M11 { get; set; }
        public Nullable<decimal> M12 { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
        public string ProductLine { get; set; }
    }
}
