//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMInvoiceDetail_Inter
    {
        public string ToStationID { get; set; }
        public string StationID { get; set; }
        public string TempSeq { get; set; }
        public string InvoiceNo { get; set; }
        public int Seq { get; set; }
        public string Debit_Credit { get; set; }
        public string CreditType { get; set; }
        public string ApprovalCBoxFlag { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public string SType { get; set; }
        public string SCurrencyCode { get; set; }
        public Nullable<double> STransactionRate { get; set; }
        public string SAmount { get; set; }
        public string SVAT { get; set; }
        public Nullable<double> SVATRate { get; set; }
        public string SVATAmount { get; set; }
        public string SVATHAmount { get; set; }
        public string STotalAmount { get; set; }
        public string SLocalEquiv { get; set; }
        public string InvSAmount { get; set; }
        public string InvSVATAmount { get; set; }
        public string InvSTotalAmount { get; set; }
        public Nullable<System.DateTime> SUpdateDate { get; set; }
        public string SUpdateUser { get; set; }
        public Nullable<int> EVenderID { get; set; }
        public string ECurrencyCode { get; set; }
        public string EGrossAmount { get; set; }
        public string EVAT { get; set; }
        public Nullable<double> EVATRate { get; set; }
        public string EVATAmount { get; set; }
        public string EVATHAmount { get; set; }
        public string ETotalAmount { get; set; }
        public string ELocalEquiv { get; set; }
        public Nullable<System.DateTime> EEstimateDate { get; set; }
        public Nullable<double> ETransactionRate { get; set; }
        public string AVenderDoc { get; set; }
        public string ADOCDate { get; set; }
        public string ACurrencyCode { get; set; }
        public Nullable<double> ATransactionRate { get; set; }
        public string AGrossAmount { get; set; }
        public string AVATAmount { get; set; }
        public string AVATHAmount { get; set; }
        public string ATotalAmount { get; set; }
        public string ALocalEquiv { get; set; }
        public Nullable<System.DateTime> ALastAppDate { get; set; }
        public string ALastAppUser { get; set; }
        public string ARemark { get; set; }
        public string Extra { get; set; }
        public Nullable<System.DateTime> AUpdateDate { get; set; }
        public string AUpdateUser { get; set; }
        public string GPEquiv { get; set; }
        public string PrintDescription { get; set; }
        public string JournalNo { get; set; }
        public Nullable<int> JournalSeq { get; set; }
        public string ARRefInvoice { get; set; }
        public string ARRefSeq { get; set; }
        public string CreditFlag { get; set; }
        public string ARLJournalNo { get; set; }
        public Nullable<int> ARLJournalSeq { get; set; }
        public string ARLumpsumUser { get; set; }
        public string PJournalNo { get; set; }
        public Nullable<int> PJournalSeq { get; set; }
        public string APRefInvoice { get; set; }
        public string APRefSeq { get; set; }
        public string APLJournalNo { get; set; }
        public Nullable<int> APLJournalSeq { get; set; }
        public string APLumpsumUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string Division { get; set; }
        public string Project { get; set; }
        public string Department { get; set; }
        public int ID { get; set; }
        public string WriteOffRefNo { get; set; }
        public Nullable<System.DateTime> BatchClearDate { get; set; }
        public Nullable<int> UOM { get; set; }
        public string Unit { get; set; }
        public string SUnitRate { get; set; }
        public string EUnitRate { get; set; }
        public string Min { get; set; }
        public string TAVenderDoc { get; set; }
        public Nullable<double> TATransactionRate { get; set; }
        public string TAGrossAmount { get; set; }
        public string TAVatAmount { get; set; }
        public string CostExtra { get; set; }
        public string EstRefNo { get; set; }
        public string FunctionType { get; set; }
    }
}
