//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMJournalDetail
    {
        public string StationID { get; set; }
        public string JournalNo { get; set; }
        public int JournalSeq { get; set; }
        public string ChartofAccount { get; set; }
        public string Notes { get; set; }
        public string OriginalCurrencyCode { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public string HCurrencyCode { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string ProductLine { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BillTo { get; set; }
        public Nullable<int> VenderID { get; set; }
        public string Division { get; set; }
        public string Project { get; set; }
        public string Department { get; set; }
        public int ID { get; set; }
        public string RefNo { get; set; }
        public string RefSeq { get; set; }
    }
}
