//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMMNCARList
    {
        public string Period { get; set; }
        public string StationID { get; set; }
        public string StationCode { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string PayTerms { get; set; }
        public Nullable<int> BillTo { get; set; }
        public string BillToCode { get; set; }
        public string BillToName { get; set; }
        public string ModeCode { get; set; }
        public string MasterNo { get; set; }
        public string HouseNo { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> OpenAmount { get; set; }
        public string HomeCurrency { get; set; }
        public Nullable<int> OverDays { get; set; }
        public Nullable<decimal> OpenHomeAmount { get; set; }
        public Nullable<decimal> OpenUSDAmount { get; set; }
        public string Confirmedby { get; set; }
        public int ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
