//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMNumber_Log
    {
        public string StationID { get; set; }
        public string TypeCD { get; set; }
        public string InvYear { get; set; }
        public string InvMonth { get; set; }
        public Nullable<decimal> NumberNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int ID { get; set; }
        public int LogID { get; set; }
        public System.DateTime LogTime { get; set; }
    }
}
