//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMOPSource_Inter
    {
        public string ToStationID { get; set; }
        public string StationID { get; set; }
        public string TempSeq { get; set; }
        public string InvoiceNo { get; set; }
        public string ProductLine { get; set; }
        public string IDType { get; set; }
        public string SourceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CreditKind { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string InvoiceType { get; set; }
        public string CurrencyCode { get; set; }
        public string InvoiceAmount { get; set; }
        public string SalesAmount { get; set; }
        public string VATAmount { get; set; }
        public string CreditAmount { get; set; }
        public string OpenAmount { get; set; }
        public string ReceivedAmount { get; set; }
        public string RecordFlag { get; set; }
        public string RefInvoiceNo { get; set; }
        public string ConfirmedBy { get; set; }
        public string PrintedBy { get; set; }
        public string Master { get; set; }
        public string House { get; set; }
        public string Lot { get; set; }
        public string ModeCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Extra { get; set; }
        public string LocalFlag { get; set; }
        public Nullable<int> BillTo { get; set; }
        public string Payterms { get; set; }
        public string BillAddress { get; set; }
        public string Remark { get; set; }
        public string BillDescription { get; set; }
        public Nullable<double> BookRate { get; set; }
        public Nullable<System.DateTime> PostGLDate { get; set; }
        public byte[] Version { get; set; }
        public Nullable<int> PrintTimes { get; set; }
        public string DataStatus { get; set; }
        public int ID { get; set; }
        public string JournalNo { get; set; }
        public string LJournalNo { get; set; }
        public string LumpSumUser { get; set; }
        public Nullable<int> LJournalSeq { get; set; }
        public string ApplyNo { get; set; }
        public string ApplyFlag { get; set; }
        public string ACSFlag { get; set; }
        public string PostHAmount { get; set; }
        public string MTSNo { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
