//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMPayablePayment
    {
        public string StationID { get; set; }
        public string DocNo { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> DocAmount { get; set; }
        public Nullable<double> BookRate { get; set; }
        public string HCurrencyCode { get; set; }
        public Nullable<decimal> HDocAmount { get; set; }
        public string StatusNumber { get; set; }
        public string APTypeFlag { get; set; }
        public string StatusType { get; set; }
        public string MonthEnd { get; set; }
        public Nullable<decimal> OpenAmount { get; set; }
        public Nullable<decimal> HOpenAmount { get; set; }
        public Nullable<decimal> StatusAmount { get; set; }
        public Nullable<decimal> HStatusAmount { get; set; }
        public string ACSPeriod { get; set; }
        public Nullable<double> MonthBookRate { get; set; }
        public Nullable<decimal> UnrealizeGainLoss { get; set; }
        public Nullable<decimal> RealizedGainLoss { get; set; }
        public Nullable<decimal> TotalUnrealizeGainLoss { get; set; }
        public Nullable<decimal> TotalRealizedGainLoss { get; set; }
        public string JournalNo { get; set; }
        public Nullable<decimal> JournalSeq { get; set; }
        public string DChartOfAccount { get; set; }
        public string CChartOfAccount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
    }
}
