//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMPaymentInfo
    {
        public string StationID { get; set; }
        public string Type { get; set; }
        public string PaymentType { get; set; }
        public string PaymentNumber { get; set; }
        public Nullable<int> VenderID { get; set; }
        public string BankA_C { get; set; }
        public Nullable<System.DateTime> GLDate { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> BookRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string HCurrencyCode { get; set; }
        public Nullable<decimal> HAmount { get; set; }
        public string BankA_CCharge { get; set; }
        public string BankChargeCurrencyCode { get; set; }
        public Nullable<decimal> BankChargeAmount { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ReversalYN { get; set; }
        public string JournalNo { get; set; }
        public string RJournalNo { get; set; }
        public Nullable<System.DateTime> RGLDate { get; set; }
        public string RNotes { get; set; }
        public string RUser { get; set; }
        public string ChequeTitle { get; set; }
        public string LocalAmount { get; set; }
        public Nullable<int> PrintTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
        public string BankReconciliationCashed { get; set; }
        public string Notes { get; set; }
        public int seq { get; set; }
        public string ApplyActive { get; set; }
    }
}
