//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMPeriodicalTemplateDetail
    {
        public decimal IDNO { get; set; }
        public string SEQ { get; set; }
        public int BillTO { get; set; }
        public Nullable<int> ChargeCate { get; set; }
        public int ChargeID { get; set; }
        public string MSubject { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Amount { get; set; }
        public string Subject { get; set; }
        public string InvoiceNO { get; set; }
        public string TempSeq { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
    }
}
