//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMTempAsset
    {
        public string AccumulatedDepreciationCOA { get; set; }
        public string OriginalCurrency { get; set; }
        public Nullable<decimal> OriginalAmount { get; set; }
        public Nullable<decimal> HomeAmount { get; set; }
        public Nullable<decimal> OtherCostAmount { get; set; }
        public string Division { get; set; }
        public string Project { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> NetBookValue { get; set; }
        public decimal ID { get; set; }
        public string AssetClassCOA { get; set; }
    }
}
