//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMTempTaxInvoiceMaster
    {
        public string StationID { get; set; }
        public string YYMonth { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Source { get; set; }
        public string IDType { get; set; }
        public string SourceID { get; set; }
        public Nullable<int> BillTo { get; set; }
        public string InvType { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> HomeCurrencyRate { get; set; }
        public string Master { get; set; }
        public string House { get; set; }
        public string Lot { get; set; }
        public Nullable<decimal> SalesAmount { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> ARAmount { get; set; }
        public string InvoiceType { get; set; }
        public string PrintedBy { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int ID { get; set; }
    }
}
