//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMTemplateJournalEntry
    {
        public string StationID { get; set; }
        public int JournalSeq { get; set; }
        public string TemplateID { get; set; }
        public string RefStationID { get; set; }
        public string TemplateDescription { get; set; }
        public string Notes { get; set; }
        public string ChartofAccount { get; set; }
        public string Description { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string AccountNotes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
        public Nullable<double> Percentage { get; set; }
    }
}
