//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMToACSAPTemp
    {
        public string StationID { get; set; }
        public string Source { get; set; }
        public int VenderID { get; set; }
        public string DocNo { get; set; }
        public int Seq { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<double> ACSRate { get; set; }
        public string ChangeCurrencyCode { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
        public string UploadPeriod { get; set; }
        public string SettlementFlag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public int ID { get; set; }
    }
}
