//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMUnapprovedCost
    {
        public string Period { get; set; }
        public string StationID { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string SID { get; set; }
        public string Lot { get; set; }
        public string Master { get; set; }
        public string House { get; set; }
        public string ModeCode { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> ChargeCodeID { get; set; }
        public string ECurrencyCode { get; set; }
        public Nullable<decimal> EGrossAmount { get; set; }
        public Nullable<decimal> EVATAmount { get; set; }
        public Nullable<decimal> ETotalAmount { get; set; }
        public Nullable<decimal> ELocalEquiv { get; set; }
        public Nullable<decimal> BookRate { get; set; }
        public string COA { get; set; }
        public Nullable<decimal> HAmount { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> VATDebit { get; set; }
        public Nullable<decimal> VATCredit { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int ID { get; set; }
    }
}
