//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICWebTrackMaster
    {
        public string ProductLine { get; set; }
        public int ID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string H_CNEE { get; set; }
        public Nullable<decimal> H_CWT { get; set; }
        public string H_DEPT { get; set; }
        public string H_DSTN { get; set; }
        public string H_Description { get; set; }
        public Nullable<System.DateTime> H_ISSUEDATE { get; set; }
        public string H_NO { get; set; }
        public string H_Notify { get; set; }
        public Nullable<int> H_PCS { get; set; }
        public string H_SHIPPER { get; set; }
        public string H_WTUOM { get; set; }
        public string M_CNEE { get; set; }
        public string M_SHIPPER { get; set; }
        public string M_DEPT { get; set; }
        public string M_DSTN { get; set; }
        public string M_NO { get; set; }
        public string M_ISSUER { get; set; }
        public string M_LOTNO { get; set; }
        public string ExtraValue1 { get; set; }
        public string ExtraValue2 { get; set; }
        public string ExtraValue3 { get; set; }
        public string ExtraValue5 { get; set; }
        public string ExtraValue4 { get; set; }
        public string MileStone { get; set; }
        public string FromStation { get; set; }
        public int isWebTracking { get; set; }
        public int isEDIMilestone { get; set; }
    }
}
