//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jane
    {
        public Nullable<int> CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string AppCreditTerm { get; set; }
        public string CreditLimitCurr { get; set; }
        public string CreditLimit { get; set; }
        public string MNCCode { get; set; }
        public Nullable<decimal> AROutstandingAmt { get; set; }
        public string OwnerStation { get; set; }
        public string LeadOwner { get; set; }
        public Nullable<decimal> not_overdue { get; set; }
        public Nullable<decimal> C1_7 { get; set; }
        public Nullable<decimal> C8_30 { get; set; }
        public Nullable<decimal> C31_45 { get; set; }
        public Nullable<decimal> C46_60 { get; set; }
        public Nullable<decimal> C61_75 { get; set; }
        public Nullable<decimal> C76_90 { get; set; }
        public Nullable<decimal> C91_1_Year { get; set; }
        public Nullable<decimal> Over_1_Year { get; set; }
    }
}
