//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIFINMaster
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public Nullable<decimal> CurrRatio { get; set; }
        public Nullable<decimal> FixedAsset2EquRatio { get; set; }
        public Nullable<decimal> DebtToEquRatio { get; set; }
        public Nullable<decimal> DepOut { get; set; }
        public Nullable<decimal> TPAYMENT { get; set; }
        public Nullable<decimal> ADVANCE { get; set; }
        public Nullable<decimal> IOFFLIABPAYAcc { get; set; }
        public Nullable<decimal> IOFFAsstReveAcc { get; set; }
        public Nullable<decimal> ICOMLIABPayAcc { get; set; }
        public Nullable<decimal> ICOMAsstReveAcc { get; set; }
        public Nullable<decimal> AROverDaysRatio { get; set; }
        public Nullable<decimal> RevenueP { get; set; }
        public Nullable<decimal> GPP { get; set; }
        public Nullable<decimal> NPP { get; set; }
        public Nullable<decimal> OpOhVSBugt { get; set; }
        public Nullable<decimal> NPAchiRatio { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
