//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIType
    {
        public int ID { get; set; }
        public int ProductLineID { get; set; }
        public string TypeCode { get; set; }
        public string DataTable { get; set; }
        public string DataColumn { get; set; }
        public string DataCalculate { get; set; }
        public string TypeName { get; set; }
        public string TypeDescription { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Unit { get; set; }
        public string Conditions { get; set; }
    }
}
