//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public int Id { get; set; }
        public string StationId { get; set; }
        public System.Guid PageId { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
        public double LoadSeconds { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
