//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MBRawData
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int EPID { get; set; }
        public string HomeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> NetProfitBeforeTax { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> AROutAsOf { get; set; }
        public Nullable<decimal> BadDebt { get; set; }
        public Nullable<decimal> AddBadDebt { get; set; }
        public Nullable<decimal> LessBadDebt { get; set; }
        public Nullable<decimal> PriorARC { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
