//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMMilestoneRule
    {
        public int ID { get; set; }
        public int MSID { get; set; }
        public string RuleName { get; set; }
        public Nullable<int> OriginCountryID { get; set; }
        public Nullable<int> DestCountryID { get; set; }
        public Nullable<int> OriginCityID { get; set; }
        public Nullable<int> DestCityID { get; set; }
        public string ServiceLevel { get; set; }
        public int MilestonIDFrom { get; set; }
        public int MilestonIDTo { get; set; }
        public string RuleTime { get; set; }
        public string RuleTimeUnit { get; set; }
        public bool IsExceptionWeekend { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
