//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSpeer_topologyresponse
    {
        public Nullable<int> request_id { get; set; }
        public string peer { get; set; }
        public Nullable<int> peer_version { get; set; }
        public string peer_db { get; set; }
        public Nullable<int> originator_id { get; set; }
        public Nullable<int> peer_conflict_retention { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string connection_info { get; set; }
    }
}
