//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTPOD
    {
        public int ID { get; set; }
        public int MTSDataID { get; set; }
        public int MTSSeq { get; set; }
        public string FLTNo { get; set; }
        public Nullable<System.DateTime> DocumentPickupDate { get; set; }
        public string ReleaseNo { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> NotifyParty { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public string NotifyType { get; set; }
        public Nullable<int> DocReleaseParty { get; set; }
        public Nullable<System.DateTime> DocReleaseDate { get; set; }
        public string DocReleaseType { get; set; }
        public string DocReleaseSignby { get; set; }
        public string CustomReleaseNo { get; set; }
        public Nullable<System.DateTime> CustomReleaseDate { get; set; }
        public Nullable<System.DateTime> LicenseDate { get; set; }
        public Nullable<int> CargoReleaseParty { get; set; }
        public Nullable<System.DateTime> CargoReleaseDate { get; set; }
        public string CargoReleaseType { get; set; }
        public string CargoReleaseSignby { get; set; }
        public Nullable<System.DateTime> CTNUnStuffDate { get; set; }
        public string Remarks { get; set; }
        public byte[] Version { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
