//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class O7512
    {
        public int ID { get; set; }
        public string Mode { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string StationID { get; set; }
        public string EntryType { get; set; }
        public string EntryNo { get; set; }
        public string EntryNoR { get; set; }
        public string ClassOfEntry { get; set; }
        public string Port { get; set; }
        public string PortDate { get; set; }
        public string DistNo { get; set; }
        public string PortCode { get; set; }
        public string PortOfUnlading { get; set; }
        public string PortOf { get; set; }
        public string PortOfDate { get; set; }
        public string ImportBy { get; set; }
        public string InBondVia { get; set; }
        public string CustomsAt { get; set; }
        public string FinalDest { get; set; }
        public string CNEE { get; set; }
        public string PortLading { get; set; }
        public string BLNo { get; set; }
        public string SailingDate { get; set; }
        public string ImportedOn { get; set; }
        public string Flag { get; set; }
        public string FlagOn { get; set; }
        public string FlagVia { get; set; }
        public string ExportFrom { get; set; }
        public string ExportOn { get; set; }
        public string GoodsAt { get; set; }
        public string Marks { get; set; }
        public string Desc { get; set; }
        public string Weight { get; set; }
        public string Value { get; set; }
        public string Rate { get; set; }
        public string Duty { get; set; }
        public string GONO { get; set; }
        public string ExportationFor { get; set; }
        public string DDCustomsAt { get; set; }
        public string CustomsSealsNo { get; set; }
        public string WithdrawnBy1 { get; set; }
        public string WithdrawnBy2 { get; set; }
        public string WithdrawnBy3 { get; set; }
        public string WithdrawnBy4 { get; set; }
        public string Carrier { get; set; }
        public string IRSNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpatedDT { get; set; }
        public string IfWithDrawn { get; set; }
        public string ImporterIRSNo { get; set; }
        public string WithdrawnBy5 { get; set; }
    }
}
