//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBKContainer
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string CNTRNo { get; set; }
        public string SealNo { get; set; }
        public string ContainerType { get; set; }
        public Nullable<int> PCS { get; set; }
        public string NatureOfCargo { get; set; }
        public string HarmonizedCode { get; set; }
        public Nullable<int> NumberOfPackage { get; set; }
        public Nullable<decimal> ContainerWT { get; set; }
        public Nullable<decimal> ContainerCBM { get; set; }
        public string PackageType { get; set; }
        public string PackageTypeDesc { get; set; }
        public string GoodsDesc { get; set; }
        public Nullable<int> OBKMainID { get; set; }
        public string EquipmentSupplierCode { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ContainerTypeText { get; set; }
        public string PackageTypeText { get; set; }
        public string PackageTypeDescText { get; set; }
        public string EquipmentSupplierText { get; set; }
        public string NatureOfCargoText { get; set; }
        public string ContainerTypeHQID { get; set; }
        public string PackageTypeHQID { get; set; }
    }
}
