//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEAMS_HEADER
    {
        public string UUID { get; set; }
        public int ID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string IssuerSCAC { get; set; }
        public string PreCarrierReceipt { get; set; }
        public string StatusIndicator { get; set; }
        public string AmendmentCode { get; set; }
        public string BookingNo { get; set; }
        public string SplitBill { get; set; }
        public string HandlingGroup { get; set; }
        public string SNPPartyCode { get; set; }
        public string AdditionalSNPParties { get; set; }
        public string NotifyPartyCode2 { get; set; }
        public Nullable<int> TotalNetWeight { get; set; }
        public string TotalNetWeightUOM { get; set; }
        public Nullable<int> TotalVolume { get; set; }
        public string TotalVolumeUOM { get; set; }
        public string HarmonizedCode { get; set; }
        public Nullable<int> CashValue { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string OceanVessel { get; set; }
        public string OceanVoyage { get; set; }
        public string VesselName { get; set; }
        public string SCACCode { get; set; }
        public string VesselFlag { get; set; }
        public string PDischarge { get; set; }
        public string PLoading { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public string HBLNo { get; set; }
        public string PDelivery { get; set; }
        public string PReceipt { get; set; }
        public string CoLoader { get; set; }
        public string MBLNO { get; set; }
        public string AgencyUniqueCode { get; set; }
        public string HazardCode { get; set; }
        public string HazardCodeQualifier { get; set; }
        public string UVICode { get; set; }
        public string UnladingForeignPort { get; set; }
        public string ISF5INDICATOR { get; set; }
        public string commoditycode { get; set; }
        public string ShipmentType { get; set; }
        public string StationID { get; set; }
        public string Status { get; set; }
        public string ACKMsg { get; set; }
        public string PurposeCode { get; set; }
        public string TypeOfEntry { get; set; }
        public string FirstPortOfCall { get; set; }
    }
}
