//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEAMS
    {
        public int ID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string IssuerSCAC { get; set; }
        public string PreCarrierReceipt { get; set; }
        public string StatusIndicator { get; set; }
        public string AmendmentCode { get; set; }
        public string BookingNo { get; set; }
        public string SplitBill { get; set; }
        public string HandlingGroup { get; set; }
        public string SNPPartyCode { get; set; }
        public string AdditionalSNPParties { get; set; }
        public string NotifyPartyCode2 { get; set; }
        public Nullable<int> TotalNetWeight { get; set; }
        public string TotalNetWeightUOM { get; set; }
        public Nullable<int> TotalVolume { get; set; }
        public string TotalVolumeUOM { get; set; }
        public string HarmonizedCode { get; set; }
        public Nullable<int> CashValue { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string OceanVessel { get; set; }
        public string OceanVoyage { get; set; }
        public string VesselName { get; set; }
        public string SCACCode { get; set; }
        public string VesselFlag { get; set; }
        public string PDischarge { get; set; }
        public string PLoading { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public string HBLNo { get; set; }
        public string PDelivery { get; set; }
        public string PReceipt { get; set; }
        public string CoLoader { get; set; }
        public string MBLNO { get; set; }
        public string AgencyUniqueCode { get; set; }
        public string SHPRName { get; set; }
        public string SHPRAddress1 { get; set; }
        public string SHPRAddress2 { get; set; }
        public string SHPRCity { get; set; }
        public string SHPRState { get; set; }
        public string SHPRZip { get; set; }
        public string SHPRPhone { get; set; }
        public string SHPRCountry { get; set; }
        public string SHPRContactName { get; set; }
        public string CNEEName { get; set; }
        public string CNEEAddress1 { get; set; }
        public string CNEEAddress2 { get; set; }
        public string CNEECity { get; set; }
        public string CNEEState { get; set; }
        public string CNEEZip { get; set; }
        public string CNEEPhone { get; set; }
        public string CNEECountry { get; set; }
        public string CNEEContactName { get; set; }
        public string NTFYName { get; set; }
        public string NTFYAddress1 { get; set; }
        public string NTFYAddress2 { get; set; }
        public string NTFYCity { get; set; }
        public string NTFYState { get; set; }
        public string NTFYZip { get; set; }
        public string NTFYPhone { get; set; }
        public string NTFYCountry { get; set; }
        public string NTFYContactName { get; set; }
        public string HazardCode { get; set; }
        public string HazardCodeQualifier { get; set; }
        public string UVICode { get; set; }
        public string UnladingForeignPort { get; set; }
        public string ISF5INDICATOR { get; set; }
        public string commoditycode { get; set; }
        public string length { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string ISOequipmenttype { get; set; }
        public string loadedempty { get; set; }
        public string equipmentdesccode { get; set; }
        public string AdditionalSNPParties2 { get; set; }
        public string NotifyPartyCode1 { get; set; }
        public Nullable<int> commodityitemnumber { get; set; }
        public string CNTRNo { get; set; }
        public string SealNumber1 { get; set; }
        public string SealNumber2 { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<int> NetWeight { get; set; }
        public string NetWeightUOM { get; set; }
        public string LoadOrEmpty { get; set; }
        public string TypeOfService { get; set; }
        public string CountryOfOrigin { get; set; }
        public string Description { get; set; }
        public string Marks { get; set; }
        public string SmallestPackageType { get; set; }
        public string NTFY2Name { get; set; }
        public string NTFY2Address1 { get; set; }
        public string NTFY2Address2 { get; set; }
        public string NTFY2City { get; set; }
        public string NTFY2State { get; set; }
        public string NTFY2Zip { get; set; }
        public string NTFY2Phone { get; set; }
        public string NTFY2Country { get; set; }
        public string NTFY2ContactName { get; set; }
        public string ShipmentType { get; set; }
        public string TypeOfEntry { get; set; }
        public string FirstPortOfCall { get; set; }
    }
}
