//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEAMSISFMailLog
    {
        public int ID { get; set; }
        public Nullable<int> MBLID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string StationID { get; set; }
        public string KeyValue { get; set; }
        public Nullable<int> CustomerHQID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string MailType { get; set; }
        public string DType { get; set; }
        public string MType { get; set; }
        public Nullable<int> MilestoneID { get; set; }
        public Nullable<System.DateTime> MilestoneTime { get; set; }
        public string MilestoneStatus { get; set; }
        public string MailTo { get; set; }
        public string SendStatus { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
