//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEBookingConfirmation
    {
        public int ID { get; set; }
        public string HBLID { get; set; }
        public string Mode { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public string StationAddress { get; set; }
        public string StationTelFax { get; set; }
        public string Attention { get; set; }
        public string FeederVessel { get; set; }
        public string FeederVoyage { get; set; }
        public string OceanVessel { get; set; }
        public string OceanVoyage { get; set; }
        public string BookingNo { get; set; }
        public string ReferenceNo { get; set; }
        public string ShipCallNo { get; set; }
        public string PlaceOfDel { get; set; }
        public string PortOfLoading { get; set; }
        public string ETD { get; set; }
        public string PortOfDisCharge { get; set; }
        public string ETA { get; set; }
        public string ContainerNo { get; set; }
        public string NoOfPkags { get; set; }
        public string Goods { get; set; }
        public string GWT { get; set; }
        public string Measurement { get; set; }
        public string EqPULocation { get; set; }
        public string EqReturnLocation { get; set; }
        public string LoadingLocation { get; set; }
        public string CloseTime { get; set; }
        public string TerminalLocation { get; set; }
        public string Remarks { get; set; }
        public string FaxedBy { get; set; }
        public string FaxedDT { get; set; }
        public string PreparedBy { get; set; }
        public string PreparedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string OEType { get; set; }
    }
}
