//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEColoadBooking
    {
        public int ID { get; set; }
        public int BookingID { get; set; }
        public Nullable<int> ColoadID { get; set; }
        public string LinkStation { get; set; }
        public Nullable<int> PReceipt { get; set; }
        public Nullable<int> PLoading { get; set; }
        public Nullable<int> PDischarge { get; set; }
        public Nullable<int> PDelivery { get; set; }
        public Nullable<int> Shipper { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAddress { get; set; }
        public Nullable<int> ShipperMap { get; set; }
        public Nullable<int> CNEE { get; set; }
        public string CNEEName { get; set; }
        public string CNEEAddress { get; set; }
        public Nullable<int> CNEEMap { get; set; }
        public Nullable<int> Notify { get; set; }
        public string NotifyName { get; set; }
        public string NotifyAddress { get; set; }
        public Nullable<int> NotifyMap { get; set; }
        public Nullable<int> AlsoNotify { get; set; }
        public string AlsoNotifyName { get; set; }
        public string AlsoNotifyAddress { get; set; }
        public Nullable<int> AlsoNotifyMap { get; set; }
        public Nullable<int> Truck { get; set; }
        public string TruckName { get; set; }
        public string TruckAddress { get; set; }
        public Nullable<int> TruckMap { get; set; }
        public string CargoLoadingLocation { get; set; }
        public Nullable<System.DateTime> PReceiptETD { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PDeliveryETD { get; set; }
        public Nullable<System.DateTime> PLoadingATD { get; set; }
        public Nullable<System.DateTime> FinalDestETD { get; set; }
        public Nullable<System.DateTime> CargoAvailableDate { get; set; }
        public string Instruction { get; set; }
        public string MoveType { get; set; }
        public string FreightPayType { get; set; }
        public string NatureOfGoodsType { get; set; }
        public string LoadType { get; set; }
        public string LastMilestone { get; set; }
        public Nullable<System.DateTime> MilestoneDate1 { get; set; }
        public Nullable<System.DateTime> MilestoneDate2 { get; set; }
        public Nullable<System.DateTime> MilestoneDate3 { get; set; }
        public Nullable<System.DateTime> MilestoneDate4 { get; set; }
        public string MBLNO { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUOM { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string CBMUOM { get; set; }
        public Nullable<int> SOCount { get; set; }
        public string CTNRType { get; set; }
        public string Marks { get; set; }
        public string Description { get; set; }
        public string Send { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string Status { get; set; }
        public string OWBType { get; set; }
        public Nullable<int> HBLID { get; set; }
    }
}
