//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEDR
    {
        public int ID { get; set; }
        public Nullable<int> MBLID { get; set; }
        public string MBLNo { get; set; }
        public string StationID { get; set; }
        public string DRNo { get; set; }
        public string BLNo { get; set; }
        public string SHPR { get; set; }
        public string CNEE { get; set; }
        public string NTFY { get; set; }
        public string PreCarriage { get; set; }
        public string PReceipt { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string PLoading { get; set; }
        public string PDischarge { get; set; }
        public string PDelivery { get; set; }
        public string DEST { get; set; }
        public string CNTRNo { get; set; }
        public string SealNo { get; set; }
        public string PCS { get; set; }
        public string GoodsDesc { get; set; }
        public string GWT { get; set; }
        public string CBM { get; set; }
        public string CNTRInWords { get; set; }
        public string FRTCharge { get; set; }
        public string RevenueTons { get; set; }
        public string Rate { get; set; }
        public string Per { get; set; }
        public string PP { get; set; }
        public string CC { get; set; }
        public string ExRate { get; set; }
        public string PPAt { get; set; }
        public string CCAt { get; set; }
        public string IssuePlace { get; set; }
        public string TotalPP { get; set; }
        public string RCY { get; set; }
        public string RCFS { get; set; }
        public string RDoor { get; set; }
        public string DCY { get; set; }
        public string DCFS { get; set; }
        public string DDoor { get; set; }
        public string TempRequired { get; set; }
        public string TempF { get; set; }
        public string TempC { get; set; }
        public string Ordinary { get; set; }
        public string Reefer { get; set; }
        public string Dangerous { get; set; }
        public string Auto { get; set; }
        public string Liquid { get; set; }
        public string LiveAnimal { get; set; }
        public string Bulk { get; set; }
        public string Other { get; set; }
        public string OtherDesc { get; set; }
        public string ChangeVessel { get; set; }
        public string CanBatch { get; set; }
        public string LoadingDate { get; set; }
        public string EffectiveDate { get; set; }
        public string Amount { get; set; }
        public string PrintDate { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public string SONo { get; set; }
        public string ETD { get; set; }
        public string OPName { get; set; }
        public string OPTELNo { get; set; }
    }
}
