//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEHBLRePrintApply
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string HBLNo { get; set; }
        public string Status { get; set; }
        public string ApplyBy { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string ApplyReason { get; set; }
        public string ApprovalBy { get; set; }
        public string ApprovalStatus { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
