//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEHBLWHEntry
    {
        public int ID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string StationID { get; set; }
        public string ClientName { get; set; }
        public string ATTN { get; set; }
        public string CustomsNo { get; set; }
        public string CustomsName { get; set; }
        public string DeliveryNo { get; set; }
        public string PKGS { get; set; }
        public string GW { get; set; }
        public string VOL { get; set; }
        public string CartonType { get; set; }
        public string Marks { get; set; }
        public string POL { get; set; }
        public string ETD { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryExtra { get; set; }
        public string WarehouseName { get; set; }
        public string WarehouseAddress { get; set; }
        public string WHContact { get; set; }
        public string WHContactTEL { get; set; }
        public string CustomsDeliveryDate { get; set; }
        public string CustomsDeliveryExtra { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyATTN { get; set; }
        public string CompanyATTNTEL { get; set; }
        public string CompanyATTNFAX { get; set; }
        public string CompanyATTNEmail { get; set; }
        public string ReMark { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
    }
}
