//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEISF5PARTY
    {
        public int ID { get; set; }
        public Nullable<int> ISF5ID { get; set; }
        public string PARTY_TYPE { get; set; }
        public string PARTY_NAME { get; set; }
        public string PARTY_ID_VALUE { get; set; }
        public string PARTY_ID_TYPE { get; set; }
        public string PARTY_ID_DATE_OF_BIRTH { get; set; }
        public string PARTY_ID_COUNTRY_OF_ISSUANCE { get; set; }
        public string PARTY_OTHER_NAME { get; set; }
        public string PARTY_OTHER_NAME_TYPE { get; set; }
        public string PARTY_ADDR1_VALUE { get; set; }
        public string PARTY_ADDR1_TYPE { get; set; }
        public string PARTY_ADDR2_VALUE { get; set; }
        public string PARTY_ADDR2_TYPE { get; set; }
        public string PARTY_ADDR3_VALUE { get; set; }
        public string PARTY_ADDR3_TYPE { get; set; }
        public string PARTY_ADDR4_VALUE { get; set; }
        public string PARTY_ADDR4_TYPE { get; set; }
        public string PARTY_ADDR5_VALUE { get; set; }
        public string PARTY_ADDR5_TYPE { get; set; }
        public string PARTY_ADDR6_VALUE { get; set; }
        public string PARTY_ADDR6_TYPE { get; set; }
        public string PARTY_CITY { get; set; }
        public string PARTY_STATE { get; set; }
        public string PARTY_POSTAL_CODE { get; set; }
        public string PARTY_COUNTRY { get; set; }
        public string CRT_USR { get; set; }
        public Nullable<System.DateTime> CRT_DTM { get; set; }
        public string UPD_USR { get; set; }
        public Nullable<System.DateTime> UPD_DTM { get; set; }
    }
}
