//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OELoadingPlan
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> LoadPlanID { get; set; }
        public Nullable<int> MBLID { get; set; }
        public string LoadingPlanNo { get; set; }
        public string OceanVessel { get; set; }
        public string OceanVoyage { get; set; }
        public Nullable<int> SHPR { get; set; }
        public Nullable<int> CoLoaderAgent { get; set; }
        public string CarrierSONo { get; set; }
        public string CTNRType { get; set; }
        public string CTNRNo { get; set; }
        public string SealNo { get; set; }
        public Nullable<int> HBLCount { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> CoLoader { get; set; }
        public Nullable<int> NTFY { get; set; }
        public Nullable<int> BookingParty { get; set; }
        public Nullable<int> Carrier { get; set; }
        public string ShptType { get; set; }
        public string MoveType { get; set; }
        public string FreightPayType { get; set; }
        public Nullable<int> PReceipt { get; set; }
        public Nullable<System.DateTime> PReceiptETD { get; set; }
        public Nullable<System.DateTime> PReceiptATD { get; set; }
        public Nullable<int> PLoading { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public Nullable<System.DateTime> PLoadingATD { get; set; }
        public Nullable<int> PDischarge { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PDischargeATD { get; set; }
        public Nullable<int> PDelivery { get; set; }
        public Nullable<System.DateTime> PDeliveryETD { get; set; }
        public Nullable<System.DateTime> PDeliveryATD { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public string Instruction { get; set; }
    }
}
