//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEMBL
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string MBLType { get; set; }
        public string MBLNo { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> HBLCount { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> SHPR { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> CoLoader { get; set; }
        public Nullable<int> NTFY { get; set; }
        public Nullable<int> DELAgent { get; set; }
        public Nullable<int> BookingParty { get; set; }
        public Nullable<int> Carrier { get; set; }
        public string OceanVessel { get; set; }
        public string OceanVoyage { get; set; }
        public string FeederVessel { get; set; }
        public string FeederVoyage { get; set; }
        public string ShptType { get; set; }
        public string MoveType { get; set; }
        public string FreightPayType { get; set; }
        public Nullable<int> PReceipt { get; set; }
        public Nullable<System.DateTime> PReceiptETD { get; set; }
        public Nullable<System.DateTime> PReceiptATD { get; set; }
        public Nullable<int> PLoading { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public Nullable<System.DateTime> PLoadingATD { get; set; }
        public Nullable<int> PDischarge { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PDischargeATD { get; set; }
        public Nullable<int> PDelivery { get; set; }
        public Nullable<System.DateTime> PDeliveryETD { get; set; }
        public Nullable<System.DateTime> PDeliveryATD { get; set; }
        public Nullable<int> FinalDEST { get; set; }
        public Nullable<System.DateTime> FinalDESTETD { get; set; }
        public Nullable<System.DateTime> FinalDESTATD { get; set; }
        public string IsBookmark { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
        public string PreAlertBy { get; set; }
        public Nullable<System.DateTime> PreAlertDT { get; set; }
        public string eManifestBy { get; set; }
        public Nullable<System.DateTime> eManifestDT { get; set; }
        public Nullable<int> SrcID { get; set; }
        public string SrcStationID { get; set; }
        public string TradeType { get; set; }
        public string FCalculateType { get; set; }
        public string ServiceType { get; set; }
        public string QuoteType { get; set; }
        public string BookingNO { get; set; }
        public Nullable<int> salesperson { get; set; }
        public string NatureOfGoodsType { get; set; }
        public string IMPStation { get; set; }
        public Nullable<int> ThirdParty { get; set; }
        public string OE3PManifestSendBy { get; set; }
        public Nullable<System.DateTime> OE3PManifestSendDT { get; set; }
        public Nullable<int> AlsoNTFY { get; set; }
        public string Instruction { get; set; }
        public string RefNumber { get; set; }
        public string MTSNO { get; set; }
        public string ColoaderMBLNo { get; set; }
        public string CargoControlNo { get; set; }
        public string OEVGMSendBy { get; set; }
        public Nullable<System.DateTime> OEVGMSendDT { get; set; }
        public Nullable<bool> ExportCustoms { get; set; }
        public Nullable<bool> ImportCustoms { get; set; }
        public string ShippingTerm { get; set; }
    }
}
