//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEVGM
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string VGMFor { get; set; }
        public Nullable<int> HBLID { get; set; }
        public Nullable<int> MBLID { get; set; }
        public string CTNRType { get; set; }
        public string CTNRNo { get; set; }
        public string SealNo { get; set; }
        public string VGMMethod { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public Nullable<decimal> TareWT { get; set; }
        public string RefType { get; set; }
        public string RefNo { get; set; }
        public Nullable<decimal> VGM { get; set; }
        public string VGMUOM { get; set; }
        public Nullable<System.DateTime> WeighingDT { get; set; }
        public string SignedBy { get; set; }
        public Nullable<System.DateTime> DeclarationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public byte[] Version { get; set; }
    }
}
