//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIEntry
    {
        public int ID { get; set; }
        public int HBLID { get; set; }
        public int MBLID { get; set; }
        public Nullable<decimal> PManifest { get; set; }
        public Nullable<decimal> POutturn { get; set; }
        public Nullable<decimal> PShort { get; set; }
        public Nullable<decimal> PSurplus { get; set; }
        public Nullable<decimal> PPillaged { get; set; }
        public Nullable<decimal> PDamaged { get; set; }
        public Nullable<decimal> WManifest { get; set; }
        public Nullable<decimal> WOutturn { get; set; }
        public Nullable<decimal> WShort { get; set; }
        public Nullable<decimal> WSurplus { get; set; }
        public Nullable<decimal> WPillaged { get; set; }
        public Nullable<decimal> WDamaged { get; set; }
        public Nullable<decimal> VManifest { get; set; }
        public Nullable<decimal> VOutturn { get; set; }
        public Nullable<decimal> VShort { get; set; }
        public Nullable<decimal> VSurplus { get; set; }
        public Nullable<decimal> VPillaged { get; set; }
        public Nullable<decimal> VDamaged { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
