//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIFLading
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string HBLNo { get; set; }
        public string SONumber { get; set; }
        public string FMCNumber { get; set; }
        public string SHPR { get; set; }
        public string CNEE { get; set; }
        public string DESTAgent { get; set; }
        public string NTFY { get; set; }
        public string AlsoNTFY { get; set; }
        public string ExportReference { get; set; }
        public string Origin { get; set; }
        public string PreCarriageBy { get; set; }
        public string PReceipt { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string PLoading { get; set; }
        public string PDischarge { get; set; }
        public string Movement { get; set; }
        public string PDelivery { get; set; }
        public string CTNRInWords { get; set; }
        public string PayAt { get; set; }
        public string DateOnBoard { get; set; }
        public string NoOfOrgBL { get; set; }
        public string IssuePlaceDate { get; set; }
        public string DeclareValue { get; set; }
        public string CTNRNo { get; set; }
        public string PCS { get; set; }
        public string GoodsDesc { get; set; }
        public string GWT { get; set; }
        public string Measurement { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public string OIType { get; set; }
        public string StationInfo { get; set; }
        public string TariffCharge { get; set; }
        public string TariffCollect { get; set; }
        public string TariffCollectTotal { get; set; }
        public string TariffItemNo { get; set; }
        public string TariffPrepaid { get; set; }
        public string TariffPrepaidTotal { get; set; }
        public string Marks { get; set; }
        public string SumPCS { get; set; }
        public string SumGWT { get; set; }
        public string SumCBM { get; set; }
        public string HBLRemarks { get; set; }
    }
}
