//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OIINBondENDouane
    {
        public int ID { get; set; }
        public string HBLID { get; set; }
        public string Mode { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public string StationAddress { get; set; }
        public string StationTel { get; set; }
        public string StationFAX { get; set; }
        public string USPort { get; set; }
        public string InTransit { get; set; }
        public string ManifestFrom { get; set; }
        public string ManifestTo { get; set; }
        public string CNEEInfo { get; set; }
        public string SHPRInfo { get; set; }
        public string AcquittalNo { get; set; }
        public string CarrierCode { get; set; }
        public string CargoControlNo { get; set; }
        public string PreviousCargoControlNo { get; set; }
        public string PKGS { get; set; }
        public string Marks { get; set; }
        public string WT { get; set; }
        public string LotNoAndHBLNo { get; set; }
        public string PLanding { get; set; }
        public string Carrier { get; set; }
        public string CustomsClearBy { get; set; }
        public string CustomsTEL { get; set; }
        public string CustomsFAX { get; set; }
        public string LocationGoods { get; set; }
        public string LocationTEL { get; set; }
        public string LocationFAX { get; set; }
        public string Vehicle { get; set; }
        public string CartageBy { get; set; }
        public string ETA { get; set; }
        public string Storage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string ReportName { get; set; }
    }
}
