//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITurnoverLetter
    {
        public int ID { get; set; }
        public string HBLID { get; set; }
        public string Mode { get; set; }
        public string StationID { get; set; }
        public string StationName { get; set; }
        public string StationAddress { get; set; }
        public string StationTelFax { get; set; }
        public string Attention { get; set; }
        public string CNEE { get; set; }
        public string FreightLocation { get; set; }
        public string MasterBLNo { get; set; }
        public string HouseBLNo { get; set; }
        public string AMSBLNo { get; set; }
        public string SubHBLNo { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string PortLoading { get; set; }
        public string PortDischarge { get; set; }
        public string LastFreeDay { get; set; }
        public string PlaceDelivery { get; set; }
        public string ITNo { get; set; }
        public string ITDate { get; set; }
        public string ITPort { get; set; }
        public string ContainerNo { get; set; }
        public string NoOfPkgs { get; set; }
        public string Goods { get; set; }
        public string GWT { get; set; }
        public string Measurement { get; set; }
        public string Remarks { get; set; }
        public string PreparedBy { get; set; }
        public string PreparedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
