//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPACDetail
    {
        public int ID { get; set; }
        public int SummaryID { get; set; }
        public string PLCode { get; set; }
        public string Mode { get; set; }
        public string IDType { get; set; }
        public int SID { get; set; }
        public string LotNo { get; set; }
        public Nullable<int> ActionType { get; set; }
        public string NewLotNo { get; set; }
        public string Remark { get; set; }
    }
}
