//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCBSA_RES
    {
        public int ID { get; set; }
        public string VOY { get; set; }
        public string StationID { get; set; }
        public string ProductLine { get; set; }
        public string FIL { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string HBL { get; set; }
        public string STATUS { get; set; }
        public string TXT { get; set; }
        public Nullable<System.DateTime> DTM { get; set; }
    }
}
