//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCBSA
    {
        public int ID { get; set; }
        public string ProductLine { get; set; }
        public string StationID { get; set; }
        public Nullable<int> HBLID { get; set; }
        public string CCN { get; set; }
        public string PrimaryCCN { get; set; }
        public string AmendmentCode { get; set; }
        public string MovementType { get; set; }
        public string TransportMode { get; set; }
        public string DischargeOffice { get; set; }
        public string DischargeOfficeCode { get; set; }
        public string DischargeWarehouse { get; set; }
        public string DestinationOffice { get; set; }
        public string DestinationOfficeCode { get; set; }
        public string DestinationWarehouse { get; set; }
        public string Consolidated { get; set; }
        public string HazardousContact { get; set; }
        public string HazardousContactPhone { get; set; }
        public string HazardousInstructions { get; set; }
        public Nullable<int> Weight { get; set; }
        public string WeightUOM { get; set; }
        public Nullable<int> Volume { get; set; }
        public string VolumeUOM { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] Version { get; set; }
        public string SHPRName { get; set; }
        public string SHPRAddress1 { get; set; }
        public string SHPRAddress2 { get; set; }
        public string SHPRCity { get; set; }
        public string SHPRState { get; set; }
        public string SHPRZip { get; set; }
        public string SHPRPhone { get; set; }
        public string SHPRCountry { get; set; }
        public string SHPRContactName { get; set; }
        public string CNEEName { get; set; }
        public string CNEEAddress1 { get; set; }
        public string CNEEAddress2 { get; set; }
        public string CNEECity { get; set; }
        public string CNEEState { get; set; }
        public string CNEEZip { get; set; }
        public string CNEEPhone { get; set; }
        public string CNEECountry { get; set; }
        public string CNEEContactName { get; set; }
        public string NTFYName { get; set; }
        public string NTFYAddress1 { get; set; }
        public string NTFYAddress2 { get; set; }
        public string NTFYCity { get; set; }
        public string NTFYState { get; set; }
        public string NTFYZip { get; set; }
        public string NTFYPhone { get; set; }
        public string NTFYCountry { get; set; }
        public string NTFYContactName { get; set; }
        public string ConsolName { get; set; }
        public string ConsolAddress1 { get; set; }
        public string ConsolAddress2 { get; set; }
        public string ConsolCity { get; set; }
        public string ConsolState { get; set; }
        public string ConsolZip { get; set; }
        public string ConsolPhone { get; set; }
        public string ConsolCountry { get; set; }
        public string ConsolContactName { get; set; }
        public string SNPPartyCode { get; set; }
        public string SNPPartyType { get; set; }
        public string SNPParty2Code { get; set; }
        public string SNPParty2Type { get; set; }
        public string Instructions { get; set; }
    }
}
