//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCBSACodeMapping
    {
        public int ID { get; set; }
        public string CodeType { get; set; }
        public string SCodeID { get; set; }
        public string SCode { get; set; }
        public string SCodeName { get; set; }
        public string EName { get; set; }
        public string CBSALocCode { get; set; }
        public string SubLocationID { get; set; }
    }
}
