//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCBSA_SCN
    {
        public int ID { get; set; }
        public string VOY { get; set; }
        public string StationID { get; set; }
        public Nullable<int> CBSAID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string ContactName { get; set; }
        public Nullable<System.DateTime> CRT_TM { get; set; }
        public string CRT_BY { get; set; }
        public Nullable<System.DateTime> UPT_TM { get; set; }
        public string UPT_BY { get; set; }
    }
}
