//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPMilestoneFactData
    {
        public int ID { get; set; }
        public string PL { get; set; }
        public string KeyValue { get; set; }
        public Nullable<int> CurrentMilestoneID { get; set; }
        public Nullable<System.DateTime> CurrentMilestone { get; set; }
        public Nullable<int> CurrentMilestone_ALL_ID { get; set; }
        public Nullable<System.DateTime> CurrentMilestone_ALL { get; set; }
        public Nullable<int> CurrentMilestone_Cus_ID { get; set; }
        public Nullable<System.DateTime> CurrentMilestone_Cus { get; set; }
        public Nullable<int> CurrentMilestone_WT_ID { get; set; }
        public Nullable<System.DateTime> CurrentMilestone_WT { get; set; }
        public Nullable<System.DateTime> M100 { get; set; }
        public Nullable<System.DateTime> M200 { get; set; }
        public Nullable<System.DateTime> M300 { get; set; }
        public Nullable<System.DateTime> M400 { get; set; }
        public Nullable<System.DateTime> M500 { get; set; }
        public Nullable<System.DateTime> M600 { get; set; }
        public Nullable<System.DateTime> M650 { get; set; }
        public Nullable<System.DateTime> M700 { get; set; }
        public Nullable<System.DateTime> M750 { get; set; }
        public Nullable<System.DateTime> M800 { get; set; }
        public Nullable<System.DateTime> M850 { get; set; }
        public Nullable<System.DateTime> M900 { get; set; }
        public Nullable<System.DateTime> M1000 { get; set; }
        public Nullable<System.DateTime> M1030 { get; set; }
        public Nullable<System.DateTime> M1050 { get; set; }
        public Nullable<System.DateTime> M1080 { get; set; }
        public Nullable<System.DateTime> M1100 { get; set; }
        public Nullable<System.DateTime> M1200 { get; set; }
        public Nullable<System.DateTime> M1300 { get; set; }
        public Nullable<System.DateTime> M1400 { get; set; }
        public Nullable<System.DateTime> M1600 { get; set; }
        public Nullable<System.DateTime> M1700 { get; set; }
        public Nullable<System.DateTime> M1800 { get; set; }
        public Nullable<System.DateTime> M1850 { get; set; }
        public Nullable<System.DateTime> M1900 { get; set; }
        public Nullable<System.DateTime> M2000 { get; set; }
        public Nullable<System.DateTime> M2100 { get; set; }
        public Nullable<System.DateTime> M2200 { get; set; }
        public Nullable<System.DateTime> M2300 { get; set; }
        public Nullable<System.DateTime> M2400 { get; set; }
        public Nullable<System.DateTime> M2500 { get; set; }
        public Nullable<System.DateTime> M2550 { get; set; }
        public Nullable<System.DateTime> M2600 { get; set; }
        public Nullable<System.DateTime> M2700 { get; set; }
        public Nullable<System.DateTime> M2800 { get; set; }
        public Nullable<System.DateTime> M2850 { get; set; }
        public Nullable<System.DateTime> M2900 { get; set; }
        public Nullable<System.DateTime> M2930 { get; set; }
        public Nullable<System.DateTime> M2950 { get; set; }
        public Nullable<System.DateTime> M2970 { get; set; }
        public Nullable<System.DateTime> M3000 { get; set; }
        public Nullable<System.DateTime> M3100 { get; set; }
        public Nullable<System.DateTime> M3200 { get; set; }
        public Nullable<System.DateTime> M3300 { get; set; }
        public Nullable<System.DateTime> M3400 { get; set; }
        public Nullable<System.DateTime> M3500 { get; set; }
        public Nullable<System.DateTime> M8000 { get; set; }
        public Nullable<System.DateTime> M100050 { get; set; }
        public Nullable<System.DateTime> M100100 { get; set; }
        public Nullable<System.DateTime> M100130 { get; set; }
        public Nullable<System.DateTime> M100150 { get; set; }
        public Nullable<System.DateTime> M100170 { get; set; }
        public Nullable<System.DateTime> M100200 { get; set; }
        public Nullable<System.DateTime> M100300 { get; set; }
        public Nullable<System.DateTime> M100400 { get; set; }
        public Nullable<System.DateTime> M100500 { get; set; }
        public Nullable<System.DateTime> M100600 { get; set; }
        public Nullable<System.DateTime> M100700 { get; set; }
        public Nullable<System.DateTime> M100800 { get; set; }
        public Nullable<System.DateTime> M100900 { get; set; }
        public Nullable<System.DateTime> M101000 { get; set; }
        public Nullable<System.DateTime> M101100 { get; set; }
        public Nullable<System.DateTime> M101150 { get; set; }
        public Nullable<System.DateTime> M101200 { get; set; }
        public Nullable<System.DateTime> M101300 { get; set; }
        public Nullable<System.DateTime> M101400 { get; set; }
        public Nullable<System.DateTime> M101500 { get; set; }
        public Nullable<System.DateTime> M101600 { get; set; }
        public Nullable<System.DateTime> M101650 { get; set; }
        public Nullable<System.DateTime> M101700 { get; set; }
        public Nullable<System.DateTime> M101800 { get; set; }
        public Nullable<System.DateTime> M101900 { get; set; }
        public Nullable<System.DateTime> M102000 { get; set; }
        public Nullable<System.DateTime> M102100 { get; set; }
        public Nullable<System.DateTime> M102200 { get; set; }
        public Nullable<System.DateTime> M102300 { get; set; }
        public Nullable<System.DateTime> M102400 { get; set; }
        public Nullable<System.DateTime> M102500 { get; set; }
        public Nullable<System.DateTime> M102600 { get; set; }
        public Nullable<System.DateTime> M102700 { get; set; }
        public Nullable<System.DateTime> M102900 { get; set; }
        public Nullable<System.DateTime> M103000 { get; set; }
        public Nullable<System.DateTime> M103100 { get; set; }
        public Nullable<System.DateTime> M103200 { get; set; }
        public Nullable<System.DateTime> M103300 { get; set; }
        public Nullable<System.DateTime> M103400 { get; set; }
        public Nullable<System.DateTime> M103500 { get; set; }
        public Nullable<System.DateTime> M103600 { get; set; }
        public Nullable<System.DateTime> M103700 { get; set; }
        public Nullable<System.DateTime> M103800 { get; set; }
        public Nullable<System.DateTime> M103900 { get; set; }
        public Nullable<System.DateTime> M104000 { get; set; }
        public Nullable<System.DateTime> M104100 { get; set; }
        public Nullable<System.DateTime> M104200 { get; set; }
        public Nullable<System.DateTime> M104300 { get; set; }
        public Nullable<System.DateTime> M104400 { get; set; }
        public Nullable<System.DateTime> M104500 { get; set; }
        public Nullable<System.DateTime> M104600 { get; set; }
        public Nullable<System.DateTime> M104700 { get; set; }
        public Nullable<System.DateTime> M104800 { get; set; }
        public Nullable<System.DateTime> M104900 { get; set; }
        public Nullable<System.DateTime> M104950 { get; set; }
        public Nullable<System.DateTime> M105000 { get; set; }
        public Nullable<System.DateTime> M105100 { get; set; }
        public Nullable<System.DateTime> M105200 { get; set; }
        public Nullable<System.DateTime> M105300 { get; set; }
        public Nullable<System.DateTime> M105400 { get; set; }
        public Nullable<System.DateTime> M105500 { get; set; }
        public Nullable<System.DateTime> M105550 { get; set; }
        public Nullable<System.DateTime> M105600 { get; set; }
        public Nullable<System.DateTime> M105700 { get; set; }
        public Nullable<System.DateTime> M105800 { get; set; }
        public Nullable<System.DateTime> M105900 { get; set; }
        public Nullable<System.DateTime> M106000 { get; set; }
        public Nullable<System.DateTime> M108000 { get; set; }
        public Nullable<System.DateTime> M1750 { get; set; }
        public Nullable<System.DateTime> M102950 { get; set; }
        public Nullable<System.DateTime> M101750 { get; set; }
        public Nullable<System.DateTime> M101760 { get; set; }
        public Nullable<System.DateTime> M101810 { get; set; }
        public Nullable<System.DateTime> M101820 { get; set; }
        public Nullable<System.DateTime> M101850 { get; set; }
        public Nullable<System.DateTime> M101860 { get; set; }
        public Nullable<System.DateTime> M101910 { get; set; }
        public Nullable<System.DateTime> M101920 { get; set; }
        public Nullable<System.DateTime> M1320 { get; set; }
        public Nullable<System.DateTime> M1330 { get; set; }
        public Nullable<System.DateTime> M1340 { get; set; }
        public Nullable<System.DateTime> M1350 { get; set; }
        public Nullable<System.DateTime> M1360 { get; set; }
        public Nullable<System.DateTime> M101930 { get; set; }
        public Nullable<System.DateTime> M101940 { get; set; }
        public Nullable<System.DateTime> M101950 { get; set; }
        public Nullable<System.DateTime> M101960 { get; set; }
        public Nullable<System.DateTime> M101970 { get; set; }
        public string CurrentMilestone_Category { get; set; }
        public string CurrentMilestone_ALL_Category { get; set; }
        public string CurrentMilestone_Cus_Category { get; set; }
        public string CurrentMilestone_WT_Category { get; set; }
        public Nullable<System.DateTime> M1090 { get; set; }
        public Nullable<System.DateTime> M1310 { get; set; }
    }
}
