//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPStatsbyMonth
    {
        public long ID { get; set; }
        public long CustomerID { get; set; }
        public string StationID { get; set; }
        public string ParentID { get; set; }
        public string Mode { get; set; }
        public string PL { get; set; }
        public int YY { get; set; }
        public int MM { get; set; }
        public Nullable<int> MNo { get; set; }
        public Nullable<int> ShptNo { get; set; }
        public Nullable<decimal> PCS { get; set; }
        public Nullable<decimal> CWT { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public Nullable<decimal> TEU { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> GP { get; set; }
        public string HomeCurrency { get; set; }
        public Nullable<decimal> RateToUSD { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
