//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPSummaryData
    {
        public int ID { get; set; }
        public string PL { get; set; }
        public string KeyValue { get; set; }
        public Nullable<decimal> FRT_NET_CUS { get; set; }
        public Nullable<decimal> FRT_VAT_CUS { get; set; }
        public Nullable<decimal> FSC_NET_CUS { get; set; }
        public Nullable<decimal> FSC_VAT_CUS { get; set; }
        public Nullable<decimal> WRS_NET_CUS { get; set; }
        public Nullable<decimal> WRS_VAT_CUS { get; set; }
        public Nullable<decimal> Other_NET_CUS { get; set; }
        public Nullable<decimal> Other_VAT_CUS { get; set; }
        public Nullable<decimal> TTL_NET_CUS { get; set; }
        public Nullable<decimal> TTL_VAT_CUS { get; set; }
        public Nullable<decimal> ORG_Other_NET_CUS { get; set; }
        public Nullable<decimal> ORG_Other_VAT_CUS { get; set; }
        public Nullable<decimal> DSTN_Other_NET_CUS { get; set; }
        public Nullable<decimal> DSTN_Other_VAT_CUS { get; set; }
        public Nullable<decimal> Surcharges_VAT_CUS { get; set; }
        public Nullable<decimal> Surcharges_NET_CUS { get; set; }
        public Nullable<decimal> Duty_NET_CUS { get; set; }
        public Nullable<decimal> Duty_VAT_CUS { get; set; }
        public Nullable<decimal> FRT_NET_ALL { get; set; }
        public Nullable<decimal> FRT_VAT_ALL { get; set; }
        public Nullable<decimal> FSC_NET_ALL { get; set; }
        public Nullable<decimal> FSC_VAT_ALL { get; set; }
        public Nullable<decimal> WRS_NET_ALL { get; set; }
        public Nullable<decimal> WRS_VAT_ALL { get; set; }
        public Nullable<decimal> Other_NET_ALL { get; set; }
        public Nullable<decimal> Other_VAT_ALL { get; set; }
        public Nullable<decimal> TTL_NET_ALL { get; set; }
        public Nullable<decimal> TTL_VAT_ALL { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> ORG_Other_NET_ALL { get; set; }
        public Nullable<decimal> ORG_Other_VAT_ALL { get; set; }
        public Nullable<decimal> DSTN_Other_NET_ALL { get; set; }
        public Nullable<decimal> DSTN_Other_VAT_ALL { get; set; }
        public Nullable<decimal> Surcharges_NET_ALL { get; set; }
        public Nullable<decimal> Surcharges_VAT_ALL { get; set; }
        public Nullable<decimal> Duty_NET_ALL { get; set; }
        public Nullable<decimal> Duty_VAT_ALL { get; set; }
        public Nullable<decimal> SalesExtra0 { get; set; }
        public Nullable<decimal> SalesExtra1 { get; set; }
        public Nullable<decimal> SalesExtra2 { get; set; }
        public Nullable<decimal> SalesExtra3 { get; set; }
        public Nullable<decimal> SalesExtra4 { get; set; }
        public Nullable<decimal> SalesExtra5 { get; set; }
        public Nullable<decimal> SalesExtra6 { get; set; }
        public Nullable<decimal> SalesExtra7 { get; set; }
        public Nullable<decimal> SalesExtra8 { get; set; }
        public Nullable<decimal> SalesExtra9 { get; set; }
        public Nullable<decimal> FRT_ECOST { get; set; }
        public Nullable<decimal> FRT_VAT_ECOST { get; set; }
        public Nullable<decimal> Other_ECOST { get; set; }
        public Nullable<decimal> Other_VAT_ECOST { get; set; }
        public Nullable<decimal> TTL_ECOST { get; set; }
        public Nullable<decimal> TTL_VAT_ECOST { get; set; }
        public Nullable<decimal> TTL_SUM_Sales { get; set; }
        public Nullable<decimal> TTL_SUM_VAT_Sales { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<decimal> SalesExtra10 { get; set; }
        public Nullable<decimal> SalesExtra11 { get; set; }
        public Nullable<decimal> SalesExtra12 { get; set; }
        public Nullable<decimal> SalesExtra13 { get; set; }
        public Nullable<decimal> SalesExtra14 { get; set; }
        public Nullable<decimal> SalesExtra15 { get; set; }
        public Nullable<decimal> SalesExtra16 { get; set; }
        public Nullable<decimal> SalesExtra17 { get; set; }
        public Nullable<decimal> SalesExtra18 { get; set; }
        public Nullable<decimal> SalesExtra19 { get; set; }
    }
}
