//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSInvoiceList
    {
        public string StationID { get; set; }
        public long ID { get; set; }
        public string PSPeriod { get; set; }
        public string PL { get; set; }
        public string CreatedStation { get; set; }
        public string CreatedStationMode { get; set; }
        public string CreatedStationLot { get; set; }
        public string HouseNo { get; set; }
        public string MasterNo { get; set; }
        public string IDType { get; set; }
        public Nullable<long> SourceID { get; set; }
        public string BillToStationCode { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string IsGenerate { get; set; }
        public Nullable<System.DateTime> GenerageDate { get; set; }
        public string InvoiceNo { get; set; }
        public string Message { get; set; }
        public string IsSendToAP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Memo { get; set; }
        public string DummyInvoiceNo { get; set; }
        public Nullable<short> IsReCal { get; set; }
        public string IsCredit { get; set; }
        public string RefInvoiceNo { get; set; }
        public string RefDummyInvoiceNo { get; set; }
    }
}
