//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSVisualShipment
    {
        public string PSPeriod { get; set; }
        public string PL { get; set; }
        public string StationID { get; set; }
        public string ModeCode { get; set; }
        public string LotNo { get; set; }
        public string MasterNo { get; set; }
        public string HouseNo { get; set; }
        public Nullable<long> Customer { get; set; }
        public string ORGStation { get; set; }
        public string DSTNStation { get; set; }
        public string PReceipt { get; set; }
        public string PDEPT { get; set; }
        public string PDSTN { get; set; }
        public string PDelivery { get; set; }
        public Nullable<long> PSOriginID { get; set; }
        public string NSType { get; set; }
        public long ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
