//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCRightV2
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string RightType { get; set; }
        public string Text { get; set; }
        public string Value { get; set; }
        public string ControlMode { get; set; }
        public string Paras { get; set; }
        public Nullable<int> SortingNo { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Show { get; set; }
        public string Help { get; set; }
        public string DisplayText { get; set; }
    }
}
