//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCustomizedForms
    {
        public int ID { get; set; }
        public string Mode { get; set; }
        public string ShipmenLevel { get; set; }
        public string FormName { get; set; }
        public string RdlcPath { get; set; }
        public string DSName { get; set; }
        public string HDName { get; set; }
        public string DTName { get; set; }
        public string HDSQL { get; set; }
        public string DTSQL { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
