//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPGlobalCodeReport
    {
        public int ID { get; set; }
        public string LotNO { get; set; }
        public string StationID { get; set; }
        public Nullable<int> Customer { get; set; }
        public string A_HNO { get; set; }
        public string A_DEPT { get; set; }
        public string A_DSTN { get; set; }
        public Nullable<decimal> VWT { get; set; }
        public Nullable<decimal> CWT { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public Nullable<decimal> A_Revenue { get; set; }
        public Nullable<decimal> A_GP { get; set; }
        public string O_HNO { get; set; }
        public string O_DEPT { get; set; }
        public string O_DSTN { get; set; }
        public Nullable<decimal> TEU { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> O_Revenue { get; set; }
        public Nullable<decimal> O_GP { get; set; }
        public Nullable<decimal> TP_Revenue { get; set; }
        public Nullable<decimal> TP_GP { get; set; }
        public Nullable<decimal> D_Revenue { get; set; }
        public Nullable<decimal> D_GP { get; set; }
        public Nullable<decimal> C_Revenue { get; set; }
        public Nullable<decimal> C_GP { get; set; }
        public Nullable<decimal> T_Revenue { get; set; }
        public Nullable<decimal> T_GP { get; set; }
        public Nullable<decimal> W_Revenue { get; set; }
        public Nullable<decimal> W_GP { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
