//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTNeAMSImStation
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int RptID { get; set; }
        public string ORG { get; set; }
        public Nullable<decimal> AWBWT { get; set; }
        public Nullable<decimal> HWBWT { get; set; }
        public Nullable<int> AWBPCS { get; set; }
        public Nullable<int> HWBPCS { get; set; }
        public Nullable<int> NoAWB { get; set; }
        public Nullable<int> NoHWB { get; set; }
        public Nullable<decimal> DNETCost { get; set; }
        public Nullable<decimal> VATSales { get; set; }
        public Nullable<decimal> NETSales { get; set; }
        public Nullable<decimal> VATCost { get; set; }
        public Nullable<decimal> NetCost { get; set; }
        public Nullable<decimal> GP { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
