//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTNrtnDAS
    {
        public int ID { get; set; }
        public string ReportByName { get; set; }
        public string ReportValue { get; set; }
        public Nullable<int> mAWBPCS { get; set; }
        public Nullable<decimal> mAWBWT { get; set; }
        public Nullable<int> HAWBPCS { get; set; }
        public Nullable<decimal> HAWBWT { get; set; }
        public Nullable<int> NoMAWB { get; set; }
        public Nullable<int> NoHAWB { get; set; }
        public Nullable<decimal> FreightCost { get; set; }
        public Nullable<decimal> FRTCost { get; set; }
        public Nullable<decimal> PPSales { get; set; }
        public Nullable<decimal> CCSales { get; set; }
        public Nullable<decimal> VATSales { get; set; }
        public Nullable<decimal> NETSales { get; set; }
        public Nullable<decimal> NetCost { get; set; }
        public Nullable<decimal> VATCost { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> GPP { get; set; }
        public string ModeCode { get; set; }
        public string IsDIMERCO { get; set; }
        public string BBAgentName { get; set; }
        public string BBAgentValue { get; set; }
    }
}
