//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTNeWMSSL
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int RptID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Project { get; set; }
        public string Customer { get; set; }
        public Nullable<int> OutboundTransNo { get; set; }
        public Nullable<int> InboundTransNo { get; set; }
        public Nullable<int> InboundPCS { get; set; }
        public Nullable<int> OutboundPCS { get; set; }
        public Nullable<decimal> LocalSales { get; set; }
        public Nullable<decimal> StorageSales { get; set; }
        public Nullable<decimal> ForeignSales { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> FixCost { get; set; }
        public Nullable<decimal> GP { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
