//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTNeOMSOEFCLCarrier
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int RptID { get; set; }
        public string Carrier { get; set; }
        public Nullable<int> NoHBL { get; set; }
        public Nullable<int> CTNR20 { get; set; }
        public Nullable<int> CTNR40 { get; set; }
        public Nullable<int> CTNR40H { get; set; }
        public Nullable<int> CTNR45 { get; set; }
        public Nullable<int> CTNROther { get; set; }
        public Nullable<decimal> TEU { get; set; }
        public Nullable<decimal> FRTPPSales { get; set; }
        public Nullable<decimal> FRTCCSales { get; set; }
        public Nullable<decimal> FRTCost { get; set; }
        public Nullable<decimal> PPSales { get; set; }
        public Nullable<decimal> CCSales { get; set; }
        public Nullable<decimal> VATSales { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> VATCost { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<decimal> GPPercentage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
