//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTNeWMSDC
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int RptID { get; set; }
        public string WarehouseCode { get; set; }
        public string ServiceMode { get; set; }
        public string CustomerID { get; set; }
        public string ProjectID { get; set; }
        public string Project { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> GITransNo { get; set; }
        public Nullable<decimal> GRTransNo { get; set; }
        public Nullable<decimal> GATransNo { get; set; }
        public Nullable<decimal> GIActQty { get; set; }
        public Nullable<decimal> GRActQty { get; set; }
        public Nullable<decimal> LocalSales { get; set; }
        public Nullable<decimal> ForeignSales { get; set; }
        public Nullable<decimal> StorageSales { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> FixCost { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<int> TransNo { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> ActQty { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
