//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAARStatus
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string ProductLineCode { get; set; }
        public Nullable<decimal> AR0 { get; set; }
        public Nullable<decimal> AR1 { get; set; }
        public Nullable<decimal> AR2 { get; set; }
        public Nullable<decimal> AR3 { get; set; }
        public Nullable<decimal> AR4 { get; set; }
        public Nullable<decimal> AR5 { get; set; }
        public Nullable<decimal> AR6 { get; set; }
        public Nullable<decimal> AR7 { get; set; }
        public Nullable<decimal> AR8 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> OverDue { get; set; }
        public string Status { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
