//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAQuoteFreightBody
    {
        public int ID { get; set; }
        public Nullable<int> FID { get; set; }
        public string Cost1 { get; set; }
        public string Cost2 { get; set; }
        public string Cost3 { get; set; }
        public string Cost4 { get; set; }
        public string Cost5 { get; set; }
        public string Cost6 { get; set; }
        public string Cost7 { get; set; }
        public string Cost8 { get; set; }
        public string Cost9 { get; set; }
        public string Cost10 { get; set; }
        public string Profit1 { get; set; }
        public string Profit2 { get; set; }
        public string Profit3 { get; set; }
        public string Profit4 { get; set; }
        public string Profit5 { get; set; }
        public string Profit6 { get; set; }
        public string Profit7 { get; set; }
        public string Profit8 { get; set; }
        public string Profit9 { get; set; }
        public string Profit10 { get; set; }
    }
}
