//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAQuoteFreights
    {
        public int ID { get; set; }
        public Nullable<int> OriginCityID { get; set; }
        public Nullable<int> DestinationCityID { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public string ServiceLevel { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string WeeklyAllotment { get; set; }
        public string Frequency { get; set; }
        public string TransitTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public string SellingRate1 { get; set; }
        public string SellingRate2 { get; set; }
        public string SellingRate3 { get; set; }
        public string SellingRate4 { get; set; }
        public string SellingRate5 { get; set; }
        public string SellingRate6 { get; set; }
        public string SellingRate7 { get; set; }
        public string SellingRate8 { get; set; }
        public string SellingRate9 { get; set; }
        public string SellingRate10 { get; set; }
        public string Commodity { get; set; }
        public Nullable<int> PloadingPortID { get; set; }
        public Nullable<int> PDischargePortID { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string OtherValue1 { get; set; }
        public string OtherValue2 { get; set; }
        public string OtherValue3 { get; set; }
    }
}
