//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAQuotes
    {
        public int ID { get; set; }
        public Nullable<int> LID { get; set; }
        public Nullable<int> PID { get; set; }
        public string QuoteNo { get; set; }
        public string Status { get; set; }
        public string AttentionTo { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> TradeTermID { get; set; }
        public Nullable<int> CreditTermID { get; set; }
        public string CreditLimitAmount { get; set; }
        public Nullable<int> CreditLimitCurrID { get; set; }
        public string Remark { get; set; }
        public string BookMark { get; set; }
        public string FRHeaderBody { get; set; }
        public string ApprovalInfo { get; set; }
        public string AcceptInfo { get; set; }
        public string CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string AcceptBy { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string sType { get; set; }
        public string OnePWD { get; set; }
    }
}
