//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAShptStatus
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string ProductLineCode { get; set; }
        public int YY { get; set; }
        public int MM { get; set; }
        public Nullable<int> CntShpt { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> GP { get; set; }
        public Nullable<int> CWT { get; set; }
        public Nullable<int> GWT { get; set; }
        public Nullable<int> TEU { get; set; }
        public Nullable<int> CBM { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
