//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLItemMaster
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string CustomerItemCode { get; set; }
        public Nullable<int> HighLevelStock { get; set; }
        public Nullable<int> LowLevelStock { get; set; }
        public string Width { get; set; }
        public string Length { get; set; }
        public string Height { get; set; }
        public Nullable<int> OnhandQTY { get; set; }
        public Nullable<int> InReceivingQTY { get; set; }
        public Nullable<int> InPickingQTY { get; set; }
        public Nullable<int> InShippingQTY { get; set; }
        public Nullable<int> AvailableQTY { get; set; }
        public Nullable<int> NetAvailableQTY { get; set; }
        public Nullable<System.DateTime> LastInventoryDT { get; set; }
        public string LastInventoryBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public string Serialized { get; set; }
        public string PartCost { get; set; }
        public string HarmonizedCode { get; set; }
        public string ECNN { get; set; }
    }
}
