//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLRNPIP_3B14
    {
        public int ID { get; set; }
        public Nullable<int> FromRole { get; set; }
        public Nullable<int> ToRole { get; set; }
        public string DocDT { get; set; }
        public string DocID { get; set; }
        public Nullable<int> CancellationParty { get; set; }
        public string ContactName { get; set; }
        public string OrderDT { get; set; }
        public string OrderNo { get; set; }
        public string RGlobalOrderAdminCode { get; set; }
        public string RDocID { get; set; }
        public string RDDT { get; set; }
        public string RDDocTypeCode { get; set; }
        public string RDParnterRoleCode { get; set; }
        public string RDLineNum { get; set; }
        public string RDDocID { get; set; }
        public string RDRevisionNum { get; set; }
        public Nullable<System.DateTime> RevDT { get; set; }
        public string MsgFile { get; set; }
        public string MsgStatus { get; set; }
        public string MsgException { get; set; }
        public Nullable<int> SLTransID { get; set; }
        public string IsConfirmSent { get; set; }
        public string InstanceIdentifier { get; set; }
        public string ConfirmStatus { get; set; }
        public string ConfirmReason { get; set; }
        public string ConfirmBy { get; set; }
        public Nullable<System.DateTime> ConfirmDT { get; set; }
    }
}
