//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLRNPIP_3B12DT
    {
        public int ID { get; set; }
        public Nullable<int> PIP_ID { get; set; }
        public string GlobalProductUnitOfMeasureCode { get; set; }
        public string isContainsHazardousMaterial { get; set; }
        public string LineNumber { get; set; }
        public string GlobalPartnerClassificationCode { get; set; }
        public string ProprietaryProductIdentifier { get; set; }
        public string revisionIdentifier { get; set; }
        public string requestedQuantity { get; set; }
        public string AcceptStatus { get; set; }
        public string AcceptQTY { get; set; }
        public string AcceptMsg { get; set; }
        public string TargetSLTransSNID { get; set; }
    }
}
