//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLTransSN
    {
        public int ID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public Nullable<int> TransHDID { get; set; }
        public Nullable<int> TransDTID { get; set; }
        public Nullable<int> TargetTransSNID { get; set; }
        public string SN { get; set; }
        public string DefectiveSN { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> OnhandQTY { get; set; }
        public Nullable<int> InReceivingQTY { get; set; }
        public Nullable<int> InPickingQTY { get; set; }
        public Nullable<int> InShippingQTY { get; set; }
        public Nullable<int> AvailableQTY { get; set; }
        public Nullable<int> NetAvailableQTY { get; set; }
    }
}
