//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLTransAdj
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> HDID { get; set; }
        public Nullable<int> DTID { get; set; }
        public Nullable<int> SNID { get; set; }
        public Nullable<int> AdjQTY { get; set; }
        public string AdjReason { get; set; }
        public string AdjStatusCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
