//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMCMRFormDetail
    {
        public int ID { get; set; }
        public int CMRID { get; set; }
        public string Marks { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public string Commodity { get; set; }
        public string HSCode { get; set; }
        public Nullable<double> GWT { get; set; }
        public Nullable<double> CBM { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
