//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMLocalChargeTemplDT
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int TemplHDID { get; set; }
        public Nullable<int> ModeCodeID { get; set; }
        public int ChargeCodeID { get; set; }
        public string Currency { get; set; }
        public string Unit { get; set; }
        public string SaleUOM { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public string SVAT { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string CostUnit { get; set; }
        public string CostUOM { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string CostCurrency { get; set; }
        public Nullable<decimal> CostMinAmount { get; set; }
        public string CostVAT { get; set; }
        public Nullable<int> SalesFixCond { get; set; }
        public Nullable<decimal> SalesFixAmount { get; set; }
        public Nullable<int> CostFixCond { get; set; }
        public Nullable<decimal> CostFixAmount { get; set; }
    }
}
