//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMMilestoneSettingGroup
    {
        public int HQID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProductLine { get; set; }
        public string TradeTerm { get; set; }
        public string ShptType { get; set; }
        public string SettingName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public string UpdateBy { get; set; }
    }
}
