//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMReportDT
    {
        public int ID { get; set; }
        public int ReportHDID { get; set; }
        public string FieldName { get; set; }
        public string Status { get; set; }
        public string PrintName { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> Selected { get; set; }
        public Nullable<double> Row { get; set; }
        public Nullable<double> Col { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string FontType { get; set; }
        public string Format { get; set; }
        public Nullable<int> Align { get; set; }
        public Nullable<bool> UseFilter { get; set; }
        public Nullable<bool> IntFilter { get; set; }
        public string FilterFrom { get; set; }
        public string FilterTo { get; set; }
        public Nullable<bool> Total { get; set; }
        public Nullable<int> Group_Level { get; set; }
        public Nullable<int> Sort_Level { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DefaultValue { get; set; }
        public string DefaultEnum { get; set; }
    }
}
