//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMScriptVersion
    {
        public short ID { get; set; }
        public string StationID { get; set; }
        public string SAScriptVersion { get; set; }
        public string AMSScriptVersion { get; set; }
        public string OMSScriptVersion { get; set; }
        public string WMSScriptVersion { get; set; }
        public string TMSScriptVersion { get; set; }
        public string DASScriptVersion { get; set; }
        public string FMSScriptVersion { get; set; }
        public string C3PSScriptVersion { get; set; }
        public string CBSScriptVersion { get; set; }
        public string SMScriptVersion1 { get; set; }
        public string PSScriptVersion { get; set; }
        public string AuditScriptVersion { get; set; }
        public string OtherScriptVersion { get; set; }
        public string DICScriptVersion { get; set; }
    }
}
