//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMToDo
    {
        public int HQID { get; set; }
        public string AWBType { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string AssignTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> Status { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
