//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMToolsReConfirm
    {
        public int ID { get; set; }
        public string Mode { get; set; }
        public string HouseNo { get; set; }
        public int Num { get; set; }
        public string HouseType { get; set; }
        public string StationID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string QuotationNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.Guid> AppliedMSGID { get; set; }
        public Nullable<System.Guid> VoidMSGID { get; set; }
        public string ApprovedReason { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.Guid> ApproveMSGID { get; set; }
        public string ServiceLevelOld { get; set; }
        public string ServiceLevel { get; set; }
        public string NatureOfGoodsOld { get; set; }
        public string NatureOfGoods { get; set; }
        public string NatureOfGoodsOldName { get; set; }
        public string NatureOfGoodsName { get; set; }
        public Nullable<int> PlaceOfReceiptOld { get; set; }
        public Nullable<int> PlaceOfReceipt { get; set; }
        public Nullable<int> PortOfDepartureOld { get; set; }
        public Nullable<int> PortOfDeparture { get; set; }
        public Nullable<int> PortOfDSTNOld { get; set; }
        public Nullable<int> PortOfDSTN { get; set; }
        public Nullable<int> PlaceOfDeliveryOld { get; set; }
        public Nullable<int> PlaceOfDelivery { get; set; }
        public string TradeTermOld { get; set; }
        public string TradeTerm { get; set; }
        public string MoveTypeOld { get; set; }
        public string MoveType { get; set; }
        public string ETDOld { get; set; }
        public string ETD { get; set; }
        public string ShipperOld { get; set; }
        public string Shipper { get; set; }
        public string CNEEOld { get; set; }
        public string CNEE { get; set; }
        public string Customer { get; set; }
        public string CustomerCode { get; set; }
        public string Carrier { get; set; }
        public string CarrierCode { get; set; }
        public string CreditTermID { get; set; }
        public string CreditTermCode { get; set; }
        public string ThirdParty { get; set; }
        public string ThirdPartyCode { get; set; }
        public string ThirdPartyOld { get; set; }
        public string ThirdPartyOldCode { get; set; }
        public string FRT { get; set; }
        public string FRTOld { get; set; }
        public string ConfirmID { get; set; }
        public string ChangeRemark { get; set; }
        public string ShptTypeOld { get; set; }
        public string ShptType { get; set; }
        public string CurrencyOld { get; set; }
        public string Currency { get; set; }
        public string CustomerOld { get; set; }
        public string CustomerCodeOld { get; set; }
        public string OtherOld { get; set; }
        public string Other { get; set; }
    }
}
