//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMToolsReOpen
    {
        public int ID { get; set; }
        public string Mode { get; set; }
        public string LotNo { get; set; }
        public int Num { get; set; }
        public Nullable<int> MID { get; set; }
        public string StationID { get; set; }
        public string MasterNo { get; set; }
        public string Category { get; set; }
        public string Remarks { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AppliedBy { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<System.Guid> AppliedMSGID { get; set; }
        public string ApprovedReason { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.Guid> ApproveMSGID { get; set; }
        public Nullable<System.Guid> VoidMSGID { get; set; }
    }
}
