//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class testSMMileStone_20180627
    {
        public int GroupID { get; set; }
        public int MilestoneID { get; set; }
        public string MilestoneName { get; set; }
        public string DetailInput { get; set; }
        public string Description { get; set; }
        public Nullable<int> SeqNum { get; set; }
        public string Usage { get; set; }
        public int ActualNum { get; set; }
        public string Mode { get; set; }
        public string InputType { get; set; }
        public string EntryControl { get; set; }
    }
}
