//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKDriver
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public System.Guid DriverID { get; set; }
        public string CompID { get; set; }
        public string DriverName { get; set; }
        public string Type { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IdentityCard { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string DriverNo { get; set; }
        public string DriverNumber { get; set; }
        public string PortNo { get; set; }
        public string BankNo { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Currency { get; set; }
        public string SalaryType { get; set; }
        public string Mark { get; set; }
        public string CIQ_NO { get; set; }
        public string ENTERPRISE_NO { get; set; }
        public string ENTERPRISE_NAME { get; set; }
        public string ENTERPRISE_PHONE { get; set; }
        public string ENTERPRISE_FAX { get; set; }
        public string ENTERPRISE_ADDRESS { get; set; }
        public string CHASSIS_NO { get; set; }
        public string CHASSIS_WEIGHT { get; set; }
        public string TRUCK_TYPE { get; set; }
        public string TRUCK_CARRIER { get; set; }
        public string ICCARDNO { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] Version { get; set; }
    }
}
