//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKStockDetailSummary
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int StockID { get; set; }
        public int TruckID { get; set; }
        public int OrderID { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CostWeight { get; set; }
        public Nullable<decimal> Items { get; set; }
        public Nullable<decimal> TotalSales_Home { get; set; }
        public Nullable<decimal> TotalSalesExt_Home { get; set; }
        public Nullable<decimal> TotalCost_Home { get; set; }
        public Nullable<decimal> TotalCostExt_Home { get; set; }
        public Nullable<decimal> ApvTotalCost_Home { get; set; }
        public Nullable<decimal> ApvTotalCostExt_Home { get; set; }
        public Nullable<decimal> TruckCost_Home { get; set; }
        public Nullable<decimal> MainDriverCost_Home { get; set; }
        public Nullable<decimal> BackupDriverCost_Home { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public Nullable<int> TruckMileage { get; set; }
        public Nullable<decimal> TotalVatSales_Home { get; set; }
        public Nullable<decimal> TotalVatSalesExt_Home { get; set; }
        public Nullable<decimal> TotalVatCost_Home { get; set; }
        public Nullable<decimal> TotalVatCostExt_Home { get; set; }
        public Nullable<decimal> ApvTotalVatCost_Home { get; set; }
        public Nullable<decimal> ApvTotalVatCostExt_Home { get; set; }
    }
}
