//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTruckToll
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int TruckID { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<System.DateTime> TollDate { get; set; }
        public Nullable<decimal> TollAmount { get; set; }
        public string Currency { get; set; }
        public string TollNumber { get; set; }
        public string Mark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
