//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKTruck
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<System.Guid> TruckID { get; set; }
        public string CompID { get; set; }
        public string TruckNo { get; set; }
        public string LicenseNo { get; set; }
        public string Type { get; set; }
        public string Modle { get; set; }
        public string Capacity { get; set; }
        public string CapacityType { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string LWHType { get; set; }
        public Nullable<int> FirstMileage { get; set; }
        public Nullable<System.DateTime> BuyData { get; set; }
        public Nullable<decimal> BuyMoney { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> DepreciationMonth { get; set; }
        public Nullable<decimal> DepreciationTotal { get; set; }
        public Nullable<int> MainDriverID { get; set; }
        public Nullable<System.Guid> MainDriverIDGUID { get; set; }
        public Nullable<int> BackupDriverID { get; set; }
        public Nullable<System.Guid> BackupDriverIDGUID { get; set; }
        public string ICCardNo { get; set; }
        public string Mark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string LicenseNo1 { get; set; }
        public string CIQ_NO { get; set; }
        public string ENTERPRISE_NO { get; set; }
        public string ENTERPRISE_NAME { get; set; }
        public string ENTERPRISE_PHONE { get; set; }
        public string ENTERPRISE_FAX { get; set; }
        public string ENTERPRISE_ADDRESS { get; set; }
        public string CHASSIS_NO { get; set; }
        public string CHASSIS_WEIGHT { get; set; }
        public string TRUCK_TYPE { get; set; }
        public string TRUCK_CARRIER { get; set; }
        public string OUTSOURCE { get; set; }
        public string OUTSOURCE_DRIVERNAME { get; set; }
        public Nullable<int> TRUCK_CARRIER_ID { get; set; }
        public Nullable<System.Guid> TRUCK_CARRIER_IDGUID { get; set; }
        public Nullable<System.DateTime> EXPIRE_DATE { get; set; }
        public string PHONE_HK { get; set; }
        public string PHONE_CN { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public byte[] Version { get; set; }
        public string VRNNo { get; set; }
    }
}
