//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_STeven
    {
        public string CustomerCode { get; set; }
        public string DSTN { get; set; }
        public string MAWBNo { get; set; }
        public string MAWBType { get; set; }
        public Nullable<int> MTNO { get; set; }
        public string FlightNo { get; set; }
        public string HAWBNo { get; set; }
        public string Customer { get; set; }
        public Nullable<int> PCS { get; set; }
        public Nullable<double> ChargeWT { get; set; }
        public Nullable<double> GrossWT { get; set; }
        public Nullable<decimal> FrtSales { get; set; }
        public Nullable<decimal> FrtCost { get; set; }
        public Nullable<decimal> PPSales { get; set; }
        public Nullable<decimal> CCSales { get; set; }
        public Nullable<decimal> VATSales { get; set; }
        public Nullable<decimal> NetSales { get; set; }
        public Nullable<decimal> VATCost { get; set; }
        public Nullable<decimal> NetCost { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> GP { get; set; }
        public string ETD { get; set; }
        public string ETA { get; set; }
        public string StationCode { get; set; }
    }
}
