//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAIRData
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string TPID { get; set; }
        public int CustomerID { get; set; }
        public string SourceStationID { get; set; }
        public string SourceType { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string MasterNo { get; set; }
        public string HouseNo { get; set; }
        public string Lot { get; set; }
        public Nullable<int> Shipper { get; set; }
        public Nullable<int> Cnee { get; set; }
        public Nullable<int> Receipt { get; set; }
        public Nullable<int> Delivery { get; set; }
        public Nullable<int> ORGN { get; set; }
        public Nullable<int> DSTN { get; set; }
        public string NetureOfGood { get; set; }
        public Nullable<int> ActPCS { get; set; }
        public string ActPCSUOM { get; set; }
        public Nullable<double> CWT { get; set; }
        public string WTUOM { get; set; }
        public Nullable<int> SalesPerson { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string LotStatus { get; set; }
        public string IsManiFast { get; set; }
        public byte[] Version { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string ServiceLevel { get; set; }
        public string Scale { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<double> VWT { get; set; }
        public string PreMaster { get; set; }
        public string ConfirmID { get; set; }
        public string ShptType { get; set; }
        public string OnboardFLT { get; set; }
        public string isDAS { get; set; }
        public string DESC { get; set; }
        public string Remark { get; set; }
        public string Marks { get; set; }
        public string SPL { get; set; }
    }
}
