//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPOceanData
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string TPID { get; set; }
        public int CustomerID { get; set; }
        public string SourceStationID { get; set; }
        public string SourceType { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string MasterNo { get; set; }
        public string HouseNo { get; set; }
        public string Lot { get; set; }
        public int Shipper { get; set; }
        public int Cnee { get; set; }
        public int Receipt { get; set; }
        public int Delivery { get; set; }
        public int POL { get; set; }
        public int POD { get; set; }
        public string NetureOfGood { get; set; }
        public string HType { get; set; }
        public Nullable<double> CBM { get; set; }
        public Nullable<int> SalesPerson { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string LotStatus { get; set; }
        public string IsManiFast { get; set; }
        public byte[] Version { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string MoveType { get; set; }
        public string Marks { get; set; }
        public string Description { get; set; }
        public string Container { get; set; }
        public Nullable<int> PCS { get; set; }
        public string PCSUOM { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WUOM { get; set; }
        public string RefNumber { get; set; }
        public string PreMaster { get; set; }
        public string ConfirmID { get; set; }
        public string ShptType { get; set; }
        public string HBLControlNo { get; set; }
        public Nullable<System.DateTime> PickupDateTime { get; set; }
        public Nullable<System.DateTime> PReceiptETD { get; set; }
        public Nullable<System.DateTime> PLoadingETD { get; set; }
        public Nullable<System.DateTime> PDischargeETD { get; set; }
        public Nullable<System.DateTime> PDeliveryETD { get; set; }
        public Nullable<System.DateTime> FinalDestETD { get; set; }
        public Nullable<System.DateTime> PLoadingATD { get; set; }
        public Nullable<int> Carrier { get; set; }
        public string BookingNo { get; set; }
    }
}
