//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_eTS_Carton_Temp
    {
        public string Jobno { get; set; }
        public string StationID { get; set; }
        public string ProjectID { get; set; }
        public string DimInboundNo { get; set; }
        public string CommInvNo { get; set; }
        public string CartonNo { get; set; }
        public string DimOutboundNo { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<System.DateTime> ScanInDateTime { get; set; }
        public Nullable<System.DateTime> ScanFullDateTime { get; set; }
        public Nullable<System.DateTime> ScanPutAway { get; set; }
        public Nullable<System.DateTime> ScanOutDateTime { get; set; }
        public string IncludedQty { get; set; }
        public string WHLocation { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Deleted { get; set; }
        public string UserDefine1 { get; set; }
        public string UserDefine2 { get; set; }
        public string UserDefine3 { get; set; }
    }
}
