//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMAPPPreGI
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<int> FromLocationID { get; set; }
        public Nullable<int> FromWarehouseID { get; set; }
        public string CartonID { get; set; }
        public int WHID { get; set; }
        public Nullable<int> OnHandQTY { get; set; }
        public Nullable<int> AvailableQty { get; set; }
        public Nullable<int> WorkOrderDTID { get; set; }
        public Nullable<int> ToLocationID { get; set; }
        public Nullable<int> ToWarehouseID { get; set; }
        public string PO { get; set; }
        public string UpdateByUserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
