//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMAutoPickCriteria
    {
        public int ID { get; set; }
        public string CriteriaName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string KeyTable1 { get; set; }
        public string KeyTableField1 { get; set; }
        public string KeyFieldOrder1 { get; set; }
        public string KeyTable2 { get; set; }
        public string KeyTableField2 { get; set; }
        public string KeyFieldOrder2 { get; set; }
        public string KeyTable3 { get; set; }
        public string KeyTableField3 { get; set; }
        public string KeyFieldOrder3 { get; set; }
        public string KeyTable4 { get; set; }
        public string KeyTableField4 { get; set; }
        public string KeyFieldOrder4 { get; set; }
        public string KeyTable5 { get; set; }
        public string KeyTableField5 { get; set; }
        public string KeyFieldOrder5 { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
    }
}
