//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMBarcodeBank
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CNEE { get; set; }
        public Nullable<int> BarcodeID { get; set; }
        public string BarcodeType { get; set; }
        public string KeyField1 { get; set; }
        public string Value1 { get; set; }
        public string KeyField2 { get; set; }
        public string Value2 { get; set; }
        public string KeyField3 { get; set; }
        public string Value3 { get; set; }
        public string KeyField4 { get; set; }
        public string Value4 { get; set; }
        public string KeyField5 { get; set; }
        public string Value5 { get; set; }
        public Nullable<int> LastSeqNo { get; set; }
    }
}
