//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMBarcode
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string BarcodeName { get; set; }
        public string Printer { get; set; }
        public string BTWFile { get; set; }
        public string PrintPrompt { get; set; }
        public Nullable<int> DefaultCopies { get; set; }
        public string Format { get; set; }
        public string LabelName { get; set; }
        public string Length { get; set; }
        public string Weight { get; set; }
        public string Remark { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<int> CacheExpireTime { get; set; }
        public Nullable<int> ForCompanyID { get; set; }
        public string SeqStatus { get; set; }
        public string KeyField1Table { get; set; }
        public string KeyField1Field { get; set; }
        public string KeyField2Table { get; set; }
        public string KeyField2Field { get; set; }
        public string KeyField3Table { get; set; }
        public string KeyField3Field { get; set; }
        public string KeyField4Table { get; set; }
        public string KeyField4Field { get; set; }
        public string KeyField5Table { get; set; }
        public string KeyField5Field { get; set; }
        public Nullable<int> Rollover { get; set; }
        public string ConversionType { get; set; }
    }
}
