//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMCarton
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string CartonName { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LengthUOM { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string WidthUOM { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string HeightUOM { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDT { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
    }
}
