//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMEDI_ITG_DOHD
    {
        public int ID { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string vendor_code { get; set; }
        public string vendor_nm { get; set; }
        public string mvt { get; set; }
        public string doc_year { get; set; }
        public string packing_no { get; set; }
        public string vendor_invoice { get; set; }
        public string doc_no { get; set; }
        public string doc_type { get; set; }
        public string customer_no { get; set; }
        public string customer_nm { get; set; }
        public string cnee { get; set; }
        public string cnee_desc { get; set; }
        public string invoice { get; set; }
        public string customer_shortnm { get; set; }
        public string customer_contact_person { get; set; }
        public string remark { get; set; }
        public string refno_1 { get; set; }
        public string refno_2 { get; set; }
        public string refno_3 { get; set; }
        public string refno_4 { get; set; }
        public string refno_5 { get; set; }
        public string refno_6 { get; set; }
        public string refno_7 { get; set; }
        public Nullable<decimal> refnum_1 { get; set; }
        public Nullable<decimal> refnum_2 { get; set; }
        public string edi_status { get; set; }
        public System.DateTime edi_date { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateBy { get; set; }
    }
}
