//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMInventoryTransfer
    {
        public int ID { get; set; }
        public Nullable<int> WorkOrderDTID { get; set; }
        public string ItemCode { get; set; }
        public string CartonId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> OnhandQty { get; set; }
        public string ScanCode { get; set; }
        public string DateCode { get; set; }
        public string CustomerPO { get; set; }
        public Nullable<int> DifferenceQty { get; set; }
        public Nullable<System.DateTime> ArrivedDockDate { get; set; }
        public string PanSize { get; set; }
        public string LotCode { get; set; }
        public string CustomerPN { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string COO { get; set; }
    }
}
