//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMPODT
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> POHDID { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<int> POQty { get; set; }
        public string QtyUOM { get; set; }
        public string ProductCode { get; set; }
        public string ScanCode { get; set; }
        public string PackingCode { get; set; }
        public Nullable<decimal> NWT { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public Nullable<decimal> CWT { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ProductLine { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ReceivedQty { get; set; }
        public Nullable<int> BackOrderQty { get; set; }
        public string Status { get; set; }
        public Nullable<int> OffSetQty { get; set; }
    }
}
