//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMPO
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string PONo { get; set; }
        public string POStatus { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string DimercoRef { get; set; }
        public string TransMode { get; set; }
        public string DocNo { get; set; }
        public string VendorRef { get; set; }
        public Nullable<int> NoOfRecords { get; set; }
        public string Supplier { get; set; }
        public string RecordType { get; set; }
        public string SONo { get; set; }
        public string JobNo { get; set; }
        public string FreightTerms { get; set; }
        public string EDISender { get; set; }
        public Nullable<System.DateTime> EDISendDT { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> NWT { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public Nullable<decimal> CWT { get; set; }
        public string Sales { get; set; }
        public string ContactName { get; set; }
        public string CustomerOrder { get; set; }
        public string TextInfo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddr1 { get; set; }
        public string SupplierAddr2 { get; set; }
        public string SupplierCity { get; set; }
        public string SupplierCountry { get; set; }
        public string SupplierPostalCode { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
