//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMProject
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string DSMTPServer { get; set; }
        public string DSMTPUser { get; set; }
        public string DSMTPPWD { get; set; }
        public string DSMTPSender { get; set; }
        public string DSMTPTitle { get; set; }
        public string DSMTPPort { get; set; }
        public Nullable<int> DWarehouseID { get; set; }
        public string DQuotation { get; set; }
        public string Description { get; set; }
        public string BarcodeFormat { get; set; }
        public string ServiceMode { get; set; }
        public string StationID { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string BizMode { get; set; }
        public string ProjectStatus { get; set; }
        public string IsAutoCartonID { get; set; }
        public string IsVerifyCartonID { get; set; }
        public string CustomCIDFieldTable { get; set; }
        public string CustomCIDFieldName { get; set; }
        public Nullable<bool> IsAPP { get; set; }
    }
}
