//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMScanGIDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string TransNo { get; set; }
        public Nullable<int> TransHDID { get; set; }
        public Nullable<int> PLID { get; set; }
        public Nullable<int> DTID { get; set; }
        public Nullable<int> TargetTransWHID { get; set; }
        public string CartonID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<int> ActQty { get; set; }
        public Nullable<int> OnHandQty { get; set; }
        public Nullable<int> Multiple { get; set; }
        public string NeedCheck { get; set; }
        public Nullable<int> GRTransID { get; set; }
        public string LocationCode { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> WareHouseID { get; set; }
        public string DateCode { get; set; }
        public string LotCode { get; set; }
        public string CustomerPN { get; set; }
        public string CustomerPO { get; set; }
        public string StationID { get; set; }
        public string IsReplication { get; set; }
        public string UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string SKU { get; set; }
        public string GIRemark { get; set; }
        public string OldCartonID { get; set; }
        public string NewSKU { get; set; }
        public string PalletID { get; set; }
        public Nullable<int> PCS { get; set; }
        public string GRPalletID { get; set; }
        public string GRPalletType { get; set; }
        public string GIPalletID { get; set; }
        public string GIPalletType { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Remark { get; set; }
        public string UpdateStatus { get; set; }
    }
}
