//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMScanCartonDetail
    {
        public int ID { get; set; }
        public int ProjectID { get; set; }
        public int TransHDID { get; set; }
        public string TransactionNo { get; set; }
        public string CartonID { get; set; }
        public string StationID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ActQty { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string LocationCode { get; set; }
        public string CargoStatus { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string IsReplication { get; set; }
        public string Status { get; set; }
        public string SKU { get; set; }
        public string OutBoxID { get; set; }
        public Nullable<decimal> GWT { get; set; }
        public string DateCode { get; set; }
        public string LotCode { get; set; }
        public Nullable<int> CTNS { get; set; }
        public Nullable<int> TransDTID { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string PalletID { get; set; }
        public string PalletType { get; set; }
        public string VarCode { get; set; }
        public string OrderSKU { get; set; }
    }
}
