//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMTransWH_Revolve
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public string SrcStationID { get; set; }
        public Nullable<int> SrcID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> TransHDID { get; set; }
        public Nullable<int> TransDTID { get; set; }
        public Nullable<int> TargetWHID { get; set; }
        public string CartonID { get; set; }
        public string Available { get; set; }
        public string CargoStatus { get; set; }
        public string ReasonCode { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> QTY { get; set; }
        public string PutAwayStatus { get; set; }
        public Nullable<System.DateTime> PutAwayDT { get; set; }
        public string PutAwayBy { get; set; }
        public string DLabelPrinted { get; set; }
        public Nullable<System.DateTime> DLabelPrintedDT { get; set; }
        public string DLabelPrientedBy { get; set; }
        public string PalletID { get; set; }
        public Nullable<int> NoOfScanCopy { get; set; }
        public Nullable<int> NoOfLabelCopy { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUOM { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string WidthUOM { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string HeightUOM { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LengthUOM { get; set; }
        public Nullable<int> OnhandQTY { get; set; }
        public Nullable<int> InReceivingQTY { get; set; }
        public Nullable<int> InPickingQTY { get; set; }
        public Nullable<int> UnavailableQTY { get; set; }
        public Nullable<int> AvailableQTY { get; set; }
        public Nullable<int> NetAvailableQTY { get; set; }
        public Nullable<int> AllocatedQTY { get; set; }
        public Nullable<System.DateTime> InventoryUpdatedDT { get; set; }
        public string Operator { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string NetWeightUOM { get; set; }
        public string PANSize { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string Extra7 { get; set; }
        public string Extra8 { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public string Extra11 { get; set; }
        public string Extra12 { get; set; }
        public Nullable<int> IsRemove { get; set; }
    }
}
