//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMTRInventory_GETEWAY_12
    {
        public string Shipper_Code { get; set; }
        public string Consignee_Code { get; set; }
        public string Carrier_Code { get; set; }
        public Nullable<System.DateTime> Requestdate { get; set; }
        public string Contractno { get; set; }
        public string Docno { get; set; }
        public string Supplier { get; set; }
        public string DateCode { get; set; }
        public string DECL1 { get; set; }
        public string DECL2 { get; set; }
        public string CustomerPO { get; set; }
        public string ItemCode { get; set; }
        public string CustomerPN { get; set; }
        public string CartonID { get; set; }
        public Nullable<double> Inventory { get; set; }
        public string Extra9 { get; set; }
        public string Extra10 { get; set; }
        public string LotNo { get; set; }
        public string COO { get; set; }
        public string Extra7 { get; set; }
        public string extra8 { get; set; }
        public string location { get; set; }
        public string HSCode { get; set; }
        public string Description { get; set; }
        public Nullable<double> unitprice { get; set; }
        public string Extra1 { get; set; }
        public string Extra11 { get; set; }
        public string Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string Extra4 { get; set; }
        public string Extra5 { get; set; }
        public string Extra6 { get; set; }
        public string ScanCode { get; set; }
        public int ID { get; set; }
        public string LotCode { get; set; }
    }
}
