//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoAppdemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMWorkOrder
    {
        public int ID { get; set; }
        public string StationID { get; set; }
        public int ProjectID { get; set; }
        public string WorkOrderNo { get; set; }
        public string WorkOrderType { get; set; }
        public string WorkOrderStatus { get; set; }
        public string JobComment { get; set; }
        public Nullable<System.DateTime> CutOffDate { get; set; }
        public string Printed { get; set; }
        public string PrintedBy { get; set; }
        public Nullable<System.DateTime> PrintedDT { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDT { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDT { get; set; }
    }
}
